In [3]:
import pandas as pd

from pathlib import Path

In [17]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', 50)

In [6]:
PROJECT_ROOT = Path().absolute().parent
PROJECT_ROOT

PosixPath('/Users/z.yang/playground/data-management-final-project')

In [18]:
df = pd.read_csv(PROJECT_ROOT / 'data' / 'fifa21 raw data v2.csv')
df

/var/folders/h9/twp789md6qzgwybcvc_bx9l00000gn/T/ipykernel_64766/2732627657.py:1: DtypeWarning: Columns (0: Hits) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(PROJECT_ROOT / 'data' / 'fifa21 raw data v2.csv')

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/210006/,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/210006/,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyne/210006/,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,Right,91,CAM,"Aug 30, 2015",NaN,€129M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silva-santos-jr/210006/,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,Right,91,LW,"Aug 3, 2017",NaN,€132M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,2018 ~ 2022,CB,178cm,66kg,Right,49,CB,"Jul 13, 2018",NaN,€100K,€1K,€70K,145,23,26,43,26,27,142,27,23,21,29,42,294,68,60,69,46,51,221,36,57,54,50,24,192,48,50,28,28,38,44,147,45,52,50,45,7,8,5,14,11,1186,255,2 ★,2★,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,2020 ~ 2021,CM,175cm,65kg,Right,51,CAM,"Aug 1, 2020",NaN,€130K,€500,€165K,211,38,42,40,56,35,219,46,40,35,50,48,305,63,64,61,51,66,226,48,58,43,47,30,193,40,23,47,47,36,38,116,32,44,40,45,12,10,9,6,8,1315,281,2 ★,2★,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley/210006/,England,18,47,65,\n\n\n\nDerry City,2019 ~ 2020,CM,179cm,74kg,Right,49,CAM,"Mar 8, 2019",NaN,€120K,€500,€131K,200,30,34,43,54,39,207,43,39,31,47,47,290,59,66,51,47,67,242,45,52,50,54,41,230,56,42,47,43,42,43,121,33,43,45,48,13,12,6,6,11,1338,285,2 ★,2★,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/210006/,China PR,20,47,57,\n\n\n\nDalian YiFang FC,2020 ~ 2022,RW,175cm,69kg,Right,48,ST,"Sep 22, 2020",NaN,€100K,€2K,€88K,215,45,52,34,42,42,194,51,35,31,31,46,254,62,55,50,33,54,235,56,45,46,48,40,190,31,25,42,46,46,45,100,26,32,42,55,14,12,9,8,12,1243,271,3 ★,2★,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,2019 ~ 2023,"CB, LB",188cm,75kg,Left,50,LB,"Jul 29, 2019",NaN,€100K,€1K,€79K,163,40,18,40,45,20,171,40,33,20,40,38,279,60,63,57,47,52,231,37,66,60,55,13,185,45,47,33,33,27,33,136,45,46,45,50,10,11,7,10,12,1215,265,3 ★,2★,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

In [23]:
df = df[df.columns[:20]]
df.head()

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/210006/,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/210006/,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyne/210006/,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,Right,91,CAM,"Aug 30, 2015",NaN,€129M
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silva-santos-jr/210006/,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,Right,91,LW,"Aug 3, 2017",NaN,€132M

In [29]:
df.columns.tolist()

['ID',
 'Name',
 'LongName',
 'photoUrl',
 'playerUrl',
 'Nationality',
 'Age',
 '↓OVA',
 'POT',
 'Club',
 'Contract',
 'Positions',
 'Height',
 'Weight',
 'Preferred Foot',
 'BOV',
 'Best Position',
 'Joined',
 'Loan Date End',
 'Value']

In [50]:
print(len(df['ID']))
print(len(df['ID'].unique()))
print(len(df['ID']) == len(df))

18979
18979
True

In [22]:
df.isnull().sum()[df.isnull().sum() > 0]

Loan Date End    17966
dtype: int64

In [28]:
df['Nationality'].unique().tolist()

['Argentina',
 'Portugal',
 'Slovenia',
 'Belgium',
 'Brazil',
 'Poland',
 'Egypt',
 'France',
 'Germany',
 'Netherlands',
 'Senegal',
 'Spain',
 'England',
 'Scotland',
 'Korea Republic',
 'Costa Rica',
 'Italy',
 'Gabon',
 'Croatia',
 'Uruguay',
 'Switzerland',
 'Serbia',
 'Slovakia',
 'Morocco',
 'Algeria',
 'Denmark',
 'Hungary',
 'Bosnia Herzegovina',
 'Nigeria',
 'Cameroon',
 'Norway',
 'Ghana',
 'Mexico',
 'Austria',
 'Albania',
 'Colombia',
 'Chile',
 'Ivory Coast',
 'Greece',
 'Finland',
 'Wales',
 'Sweden',
 'Togo',
 'Czech Republic',
 'Russia',
 'Venezuela',
 'Canada',
 'United States',
 'Guinea',
 'Montenegro',
 'Israel',
 'Republic of Ireland',
 'Ukraine',
 'Turkey',
 'Ecuador',
 'Jamaica',
 'DR Congo',
 'Australia',
 'China PR',
 'Armenia',
 'Northern Ireland',
 'North Macedonia',
 'Kosovo',
 'Mali',
 'Peru',
 'Central African Republic',
 'Iceland',
 'Burkina Faso',
 'Paraguay',
 'Japan',
 'Romania',
 'New Zealand',
 'Iran',
 'Angola',
 'Tunisia',
 'Syria',
 'Dominican Republic',
 'Cape Verde',
 'Equatorial Guinea',
 'Kenya',
 'Georgia',
 'Panama',
 'Zambia',
 'Tanzania',
 'Zimbabwe',
 'Congo',
 'South Africa',
 'Moldova',
 'Mozambique',
 'Iraq',
 'Guinea Bissau',
 'Honduras',
 'Cuba',
 'Cyprus',
 'Lithuania',
 'Estonia',
 'Madagascar',
 'Benin',
 'Curacao',
 'Saudi Arabia',
 'Gambia',
 'Uzbekistan',
 'Chad',
 'United Arab Emirates',
 'Saint Kitts and Nevis',
 'Libya',
 'Sierra Leone',
 'Philippines',
 'Liberia',
 'Bulgaria',
 'Comoros',
 'Namibia',
 'Luxembourg',
 'Trinidad & Tobago',
 'Bermuda',
 'Thailand',
 'Burundi',
 'New Caledonia',
 'Puerto Rico',
 'Bolivia',
 'Kazakhstan',
 'Antigua & Barbuda',
 'Latvia',
 'Malawi',
 'Montserrat',
 'São Tomé & Príncipe',
 'El Salvador',
 'Mauritania',
 'Jordan',
 'Eritrea',
 'Aruba',
 'Uganda',
 'Chinese Taipei',
 'Azerbaijan',
 'Afghanistan',
 'Faroe Islands',
 'Haiti',
 'Sudan',
 'Grenada',
 'Lebanon',
 'Guam',
 'Palestine',
 'Belarus',
 'Guyana',
 'Rwanda',
 'Liechtenstein',
 'Saint Lucia',
 'Papua New Guinea',
 'India',
 'Ethiopia',
 'Belize',
 'Andorra',
 'Guatemala',
 'Malta',
 'Niger',
 'Korea DPR',
 'Barbados',
 'Macau',
 'South Sudan',
 'Singapore',
 'Hong Kong',
 'Nicaragua',
 'Malaysia',
 'Indonesia']

In [30]:
df['Age'].unique().tolist()

[33,
 35,
 27,
 29,
 28,
 31,
 21,
 34,
 32,
 25,
 26,
 30,
 20,
 24,
 22,
 23,
 19,
 38,
 42,
 36,
 37,
 18,
 17,
 39,
 40,
 41,
 16,
 43,
 53]

In [31]:
df['↓OVA'].unique().tolist()

[93,
 92,
 91,
 90,
 89,
 88,
 87,
 86,
 85,
 84,
 83,
 82,
 81,
 80,
 79,
 78,
 77,
 76,
 75,
 74,
 73,
 72,
 71,
 70,
 69,
 68,
 67,
 66,
 65,
 64,
 63,
 62,
 61,
 60,
 59,
 58,
 57,
 56,
 55,
 54,
 53,
 52,
 51,
 50,
 49,
 48,
 47]

In [32]:
df['POT'].unique().tolist()

[93,
 92,
 91,
 90,
 95,
 89,
 88,
 87,
 86,
 85,
 84,
 83,
 82,
 81,
 80,
 79,
 78,
 77,
 76,
 75,
 74,
 73,
 72,
 71,
 70,
 69,
 68,
 67,
 66,
 65,
 64,
 63,
 62,
 61,
 60,
 59,
 58,
 57,
 56,
 55,
 54,
 53,
 52,
 51,
 50,
 49,
 48,
 47]

In [33]:
df['Club'].unique().tolist()

['\n\n\n\nFC Barcelona',
 '\n\n\n\nJuventus',
 '\n\n\n\nAtlético Madrid',
 '\n\n\n\nManchester City',
 '\n\n\n\nParis Saint-Germain',
 '\n\n\n\nFC Bayern München',
 '\n\n\n\nLiverpool',
 '\n\n\n\nReal Madrid',
 '\n\n\n\nChelsea',
 '\n\n\n\nTottenham Hotspur',
 '\n\n\n\nInter',
 '\n\n\n\nNapoli',
 '\n\n\n\nBorussia Dortmund',
 '\n\n\n\nManchester United',
 '\n\n\n\nArsenal',
 '\n\n\n\nLazio',
 '\n\n\n\nLeicester City',
 '\n\n\n\nBorussia Mönchengladbach',
 '\n\n\n\nReal Sociedad',
 '\n\n\n\nAtalanta',
 '\n\n\n\nOlympique Lyonnais',
 '\n\n\n\nMilan',
 '\n\n\n\nVillarreal CF',
 '\n\n\n\nRB Leipzig',
 '\n\n\n\nCagliari',
 '\n\n\n\nAjax',
 '\n\n\n\nSL Benfica',
 '\n\n\n\nAS Monaco',
 '\n\n\n\nWolverhampton Wanderers',
 '\n\n\n\nEverton',
 '\n\n\n\nFiorentina',
 '\n\n\n\nFC Porto',
 '\n\n\n\nRC Celta',
 '\n\n\n\nTorino',
 '\n\n\n\nSevilla FC',
 '\n\n\n\nGrêmio',
 '\n\n\n\nReal Betis',
 '\n\n\n\nRoma',
 '\n\n\n\nNewcastle United',
 '\n\n\n\nEintracht Frankfurt',
 '\n\n\n\nValencia CF',
 '\n\n\n\nMedipol Başakşehir FK',
 '\n\n\n\nInter Miami',
 '\n\n\n\nBayer 04 Leverkusen',
 '\n\n\n\nLevante UD',
 '\n\n\n\nCrystal Palace',
 '\n\n\n\nAthletic Club de Bilbao',
 '\n\n\n\nShanghai SIPG FC',
 '\n\n\n\nVfL Wolfsburg',
 '\n\n\n\nGuangzhou Evergrande Taobao FC',
 '\n\n\n\nAl Shabab',
 '\n\n\n\nOlympique de Marseille',
 '\n\n\n\nLos Angeles FC',
 '\n\n\n\nBeijing Sinobo Guoan FC',
 '\n\n\n\nGetafe CF',
 '\n\n\n\nSV Werder Bremen',
 '\n\n\n\nTSG 1899 Hoffenheim',
 '\n\n\n\nLOSC Lille',
 '\n\n\n\nDeportivo Alavés',
 '\n\n\n\nBurnley',
 '\n\n\n\nLeeds United',
 '\n\n\n\nFulham',
 '\n\n\n\nPFC CSKA Moscow',
 '\n\n\n\nGenoa',
 '\n\n\n\nGalatasaray SK',
 '\n\n\n\nAtlanta United',
 '\n\n\n\nAtlético Mineiro',
 '\n\n\n\nFlamengo',
 '\n\n\n\nPalmeiras',
 'No Club',
 '\n\n\n\nSão Paulo',
 '\n\n\n\nWest Ham United',
 '\n\n\n\nSD Eibar',
 '\n\n\n\nRiver Plate',
 '\n\n\n\nOGC Nice',
 '\n\n\n\nReal Valladolid CF',
 '\n\n\n\nSporting CP',
 '\n\n\n\nPSV',
 '\n\n\n\nFeyenoord',
 '\n\n\n\nClub Brugge KV',
 '\n\n\n\nShakhtar Donetsk',
 '\n\n\n\nVissel Kobe',
 '\n\n\n\nBoca Juniors',
 '\n\n\n\n1. FC Union Berlin',
 '\n\n\n\nDalian YiFang FC',
 '\n\n\n\nAS Saint-Étienne',
 '\n\n\n\nSassuolo',
 '\n\n\n\nTigres U.A.N.L.',
 '\n\n\n\nDinamo Zagreb',
 '\n\n\n\nDynamo Kyiv',
 '\n\n\n\nFluminense',
 '\n\n\n\nUdinese',
 '\n\n\n\nAston Villa',
 '\n\n\n\nStade Rennais FC',
 '\n\n\n\nBeşiktaş JK',
 '\n\n\n\nBrighton & Hove Albion',
 '\n\n\n\nHebei China Fortune FC',
 '\n\n\n\nSouthampton',
 '\n\n\n\nLokomotiv Moscow',
 '\n\n\n\nJiangsu Suning FC',
 '\n\n\n\nAl Hilal',
 '\n\n\n\nWest Bromwich Albion',
 '\n\n\n\nFenerbahçe SK',
 '\n\n\n\nFC Groningen',
 '\n\n\n\nGuangzhou R&F FC',
 '\n\n\n\nOrlando City SC',
 '\n\n\n\nSampdoria',
 '\n\n\n\nStade de Reims',
 '\n\n\n\nSheffield United',
 '\n\n\n\nSantos',
 '\n\n\n\nInternacional',
 '\n\n\n\nCoritiba',
 '\n\n\n\nCA Osasuna',
 '\n\n\n\nLA Galaxy',
 '\n\n\n\nAl Nassr',
 '\n\n\n\nSC Freiburg',
 '\n\n\n\nSC Braga',
 '\n\n\n\nOlympiacos CFP',
 '\n\n\n\nToronto FC',
 '\n\n\n\nGranada CF',
 '\n\n\n\nFC Schalke 04',
 '\n\n\n\nRC Strasbourg Alsace',
 '\n\n\n\nHertha BSC',
 '\n\n\n\nAZ Alkmaar',
 '\n\n\n\nSeattle Sounders FC',
 '\n\n\n\nMontpellier HSC',
 '\n\n\n\nShanghai Greenland Shenhua FC',
 '\n\n\n\nHamburger SV',
 '\n\n\n\nGirona FC',
 '\n\n\n\nRacing Club',
 '\n\n\n\nPortland Timbers',
 '\n\n\n\nFC Girondins de Bordeaux',
 '\n\n\n\nWatford',
 '\n\n\n\nEstudiantes de La Plata',
 '\n\n\n\nClub América',
 '\n\n\n\nVitória Guimarães',
 '\n\n\n\nSK Slavia Praha',
 '\n\n\n\nTrabzonspor',
 '\n\n\n\nRCD Espanyol',
 '\n\n\n\nFC Nantes',
 '\n\n\n\nAngers SCO',
 '\n\n\n\nCruz Azul',
 '\n\n\n\nBSC Young Boys',
 '\n\n\n\nClub León',
 '\n\n\n\nSpartak Moscow',
 '\n\n\n\nSivasspor',
 '\n\n\n\nElche CF',
 '\n\n\n\nFC Augsburg',
 '\n\n\n\nWuhan Zall',
 '\n\n\n\nParma',
 '\n\n\n\nRoyal Antwerp FC',
 '\n\n\n\nMonterrey',
 '\n\n\n\nSan Lorenzo de Almagro',
 '\n\n\n\nAC Monza',
 '\n\n\n\nClub Atlético Lanús',
 '\n\n\n\nSD Huesca',
 '\n\n\n\nDerby County',
 '\n\n\n\nKayserispor',
 '\n\n\n\nRSC Anderlecht',
 '\n\n\n\nCD Leganés',
 '\n\n\n\nVélez Sarsfield',
 '\n\n\n\nStade Brestois 29',
 '\n\n\n\nTianjin TEDA FC',
 '\n\n\n\nBirmingham City',
 '\n\n\n\nHellas Verona',
 '\n\n\n\n1. FC Köln',
 '\n\n\n\nAl Wehda',
 '\n\n\n\nBournemouth',
 '\n\n\n\nAlanyaspor',
 '\n\n\n\nBologna',
 '\n\n\n\nAmiens SC',
 '\n\n\n\nCeltic',
 '\n\n\n\nShijiazhuang Ever Bright F.C.',
 '\n\n\n\nClub Atlas',
 '\n\n\n\nAl Ahli',
 '\n\n\n\nNorwich City',
 '\n\n\n\nFatih Karagümrük S.K.',
 '\n\n\n\nClub Tijuana',
 '\n\n\n\nUniversidad Católica',
 '\n\n\n\nGoiás',
 '\n\n\n\nBenevento',
 '\n\n\n\nIndependiente',
 '\n\n\n\nQingdao Huanghai F.C.',
 '\n\n\n\nBrentford',
 '\n\n\n\nAEK Athens',
 '\n\n\n\nRacing Club de Lens',
 '\n\n\n\nOlimpia Asunción',
 '\n\n\n\nShenzhen FC',
 '\n\n\n\nÇaykur Rizespor',
 '\n\n\n\nKAA Gent',
 '\n\n\n\nNew England Revolution',
 '\n\n\n\nCádiz CF',
 '\n\n\n\n1. FSV Mainz 05',
 '\n\n\n\nVasco da Gama',
 '\n\n\n\nFC Midtjylland',
 '\n\n\n\nAl Ain FC',
 '\n\n\n\nSantos Laguna',
 '\n\n\n\nSPAL',
 '\n\n\n\nPerth Glory',
 '\n\n\n\nFC Utrecht',
 '\n\n\n\nMontreal Impact',
 '\n\n\n\nUD Almería',
 '\n\n\n\nFortaleza',
 '\n\n\n\nSpezia',
 '\n\n\n\nFC Basel 1893',
 '\n\n\n\nFC København',
 '\n\n\n\nGodoy Cruz',
 '\n\n\n\nDeportivo Toluca',
 '\n\n\n\nNacional de Montevideo',
 '\n\n\n\nAalborg BK',
 '\n\n\n\nRio Ave FC',
 '\n\n\n\nFC Metz',
 '\n\n\n\nChongqing Dangdai Lifan FC SWM Team',
 '\n\n\n\nRosenborg BK',
 '\n\n\n\nFC Red Bull Salzburg',
 '\n\n\n\nBotafogo',
 '\n\n\n\nDSC Arminia Bielefeld',
 '\n\n\n\nClub Athletico Paranaense',
 '\n\n\n\nRCD Mallorca',
 '\n\n\n\nPachuca',
 '\n\n\n\nSwansea City',
 '\n\n\n\nKRC Genk',
 '\n\n\n\nEn Avant de Guingamp',
 '\n\n\n\nLecce',
 '\n\n\n\nNîmes Olympique',
 '\n\n\n\nColo-Colo',
 '\n\n\n\nStade Malherbe Caen',
 '\n\n\n\nColumbus Crew SC',
 '\n\n\n\nJunior FC',
 '\n\n\n\nVfB Stuttgart',
 '\n\n\n\nMoreirense FC',
 '\n\n\n\nRangers FC',
 '\n\n\n\nMalmö FF',
 '\n\n\n\nShandong Luneng TaiShan FC',
 '\n\n\n\nSparta Praha',
 '\n\n\n\nHatayspor',
 '\n\n\n\nChicago Fire',
 '\n\n\n\nToulouse Football Club',
 '\n\n\n\nFC Seoul',
 '\n\n\n\nAntalyaspor',
 '\n\n\n\nDeportivo Cali',
 '\n\n\n\nKaizer Chiefs',
 '\n\n\n\nReal Zaragoza',
 '\n\n\n\nAtlético Clube Goianiense',
 '\n\n\n\nPuebla FC',
 '\n\n\n\nFortuna Düsseldorf',
 '\n\n\n\nWestern United FC',
 '\n\n\n\nAstra Giurgiu',
 '\n\n\n\nHenan Jianye FC',
 '\n\n\n\nBahia',
 '\n\n\n\nFamalicão',
 '\n\n\n\nAtiker Konyaspor',
 '\n\n\n\nPeñarol',
 '\n\n\n\nDC United',
 '\n\n\n\nNew York City FC',
 '\n\n\n\nArgentinos Juniors',
 '\n\n\n\nU.N.A.M.',
 '\n\n\n\nMinnesota United FC',
 '\n\n\n\nNottingham Forest',
 '\n\n\n\nIndependiente del Valle',
 '\n\n\n\nDefensa y Justicia',
 '\n\n\n\nPhiladelphia Union',
 "\n\n\n\nNewell's Old Boys",
 '\n\n\n\nRosario Central',
 '\n\n\n\nAtlético de San Luis',
 '\n\n\n\nFC Dallas',
 '\n\n\n\nDenizlispor',
 '\n\n\n\nYeni Malatyaspor',
 '\n\n\n\nClub Atlético Colón',
 '\n\n\n\nHouston Dynamo',
 '\n\n\n\nMillwall',
 '\n\n\n\nClube Sport Marítimo',
 '\n\n\n\nMKE Ankaragücü',
 '\n\n\n\nGuadalajara',
 '\n\n\n\nBoavista FC',
 '\n\n\n\nSporting Kansas City',
 '\n\n\n\nAtlético Nacional',
 '\n\n\n\nCD Lugo',
 '\n\n\n\nNew York Red Bulls',
 '\n\n\n\nPAOK',
 '\n\n\n\nSC Heerenveen',
 '\n\n\n\nDaegu FC',
 '\n\n\n\nPreston North End',
 '\n\n\n\nDamac FC',
 '\n\n\n\nBrescia',
 '\n\n\n\nVfL Bochum 1848',
 '\n\n\n\nVancouver Whitecaps FC',
 '\n\n\n\nSV Sandhausen',
 '\n\n\n\nRoyal Excel Mouscron',
 '\n\n\n\nDijon FCO',
 '\n\n\n\nMolde FK',
 '\n\n\n\nPanathinaikos FC',
 '\n\n\n\nLASK Linz',
 '\n\n\n\nUlsan Hyundai FC',
 '\n\n\n\nReal Salt Lake',
 '\n\n\n\nFC Luzern',
 '\n\n\n\nViktoria Plzeň',
 '\n\n\n\nOrlando Pirates',
 '\n\n\n\nAl Ittihad',
 '\n\n\n\n1. FC Nürnberg',
 '\n\n\n\nStandard de Liège',
 '\n\n\n\nRayo Vallecano',
 '\n\n\n\nClub Libertad',
 '\n\n\n\nJeonbuk Hyundai Motors',
 '\n\n\n\nWestern Sydney Wanderers',
 '\n\n\n\nUnión de Santa Fe',
 '\n\n\n\nFC Sion',
 '\n\n\n\nSydney FC',
 '\n\n\n\nHannover 96',
 '\n\n\n\nReal Sporting de Gijón',
 '\n\n\n\nFC Cincinnati',
 '\n\n\n\nESTAC Troyes',
 '\n\n\n\nSan Jose Earthquakes',
 '\n\n\n\nClub Guaraní',
 '\n\n\n\nFC Lorient',
 '\n\n\n\nGençlerbirliği SK',
 '\n\n\n\nSporting de Charleroi',
 '\n\n\n\nWisła Kraków',
 '\n\n\n\nAl Taawoun',
 '\n\n\n\nReading',
 '\n\n\n\nGazişehir Gaziantep F.K.',
 '\n\n\n\nBlackburn Rovers',
 '\n\n\n\nKashiwa Reysol',
 '\n\n\n\nFK Bodø/Glimt',
 '\n\n\n\nWillem II',
 '\n\n\n\nVitesse',
 '\n\n\n\nGil Vicente FC',
 '\n\n\n\nSønderjyskE',
 '\n\n\n\nYokohama F. Marinos',
 '\n\n\n\nFC St. Gallen',
 '\n\n\n\nClub Atlético Aldosivi',
 '\n\n\n\nGöztepe SK',
 '\n\n\n\nHolstein Kiel',
 '\n\n\n\nFC Juárez',
 '\n\n\n\nFCSB (Steaua)',
 '\n\n\n\nEttifaq FC',
 '\n\n\n\nKAS Eupen',
 '\n\n\n\nFC Tokyo',
 '\n\n\n\nMelbourne City FC',
 '\n\n\n\nUniversitatea Craiova',
 '\n\n\n\nCD Tondela',
 '\n\n\n\nWolfsberger AC',
 '\n\n\n\nCeará Sporting Club',
 '\n\n\n\nRiver Plate Asunción',
 '\n\n\n\nStoke City',
 '\n\n\n\nParis FC',
 '\n\n\n\nIFK Norrköping',
 '\n\n\n\nCrotone',
 '\n\n\n\nCardiff City',
 '\n\n\n\nAmérica de Cali',
 '\n\n\n\nAl Faisaly',
 '\n\n\n\nIndependiente Medellín',
 '\n\n\n\nPortimonense SC',
 '\n\n\n\nCD Tenerife',
 '\n\n\n\nHeracles Almelo',
 '\n\n\n\nNashville SC',
 '\n\n\n\nSK Rapid Wien',
 '\n\n\n\nKawasaki Frontale',
 '\n\n\n\nClub Necaxa',
 '\n\n\n\nChievo Verona',
 '\n\n\n\nLech Poznań',
 '\n\n\n\nAIK',
 '\n\n\n\nFK Austria Wien',
 '\n\n\n\nQuerétaro',
 '\n\n\n\n1. FC Heidenheim 1846',
 '\n\n\n\nLegia Warszawa',
 '\n\n\n\nClub Atlético Banfield',
 '\n\n\n\nOs Belenenses',
 '\n\n\n\nHuddersfield Town',
 '\n\n\n\nKSV Cercle Brugge',
 '\n\n\n\nLDU Quito',
 '\n\n\n\nGimnasia y Esgrima La Plata',
 '\n\n\n\nGamba Osaka',
 '\n\n\n\nMiddlesbrough',
 '\n\n\n\nServette FC',
 '\n\n\n\nEmpoli',
 '\n\n\n\nReal Oviedo',
 '\n\n\n\nKasimpaşa SK',
 '\n\n\n\nCFR Cluj',
 '\n\n\n\nMillonarios FC',
 '\n\n\n\nFC Paços de Ferreira',
 '\n\n\n\nSint-Truidense VV',
 '\n\n\n\nAD Alcorcón',
 '\n\n\n\nColorado Rapids',
 '\n\n\n\nDinamo Bucureşti',
 '\n\n\n\nCerezo Osaka',
 '\n\n\n\nFC Emmen',
 '\n\n\n\nSheffield Wednesday',
 '\n\n\n\nFC Erzgebirge Aue',
 '\n\n\n\nRaków Częstochowa',
 '\n\n\n\nAtlético Tucumán',
 '\n\n\n\nSV Darmstadt 98',
 '\n\n\n\nBristol City',
 '\n\n\n\nOud-Heverlee Leuven',
 '\n\n\n\nBarnsley',
 '\n\n\n\nQueens Park Rangers',
 '\n\n\n\nSangju Sangmu FC',
 '\n\n\n\nHelsingborgs IF',
 '\n\n\n\nAC Ajaccio',
 '\n\n\n\nOceânico FC',
 '\n\n\n\nClub Atlético Talleres',
 '\n\n\n\nAl Hazem',
 '\n\n\n\nSC Paderborn 07',
 '\n\n\n\nClub Atlético Huracán',
 '\n\n\n\nKV Kortrijk',
 '\n\n\n\nEl Nacional',
 '\n\n\n\nMazatlán FC',
 '\n\n\n\nAberdeen',
 '\n\n\n\nCD Mirandés',
 '\n\n\n\nSV Zulte-Waregem',
 '\n\n\n\nPiast Gliwice',
 '\n\n\n\nDjurgårdens IF',
 '\n\n\n\nCentral Córdoba',
 '\n\n\n\nWellington Phoenix',
 '\n\n\n\nDeportivo Binacional',
 '\n\n\n\nPatronato',
 '\n\n\n\nSpVgg Greuther Fürth',
 '\n\n\n\nIFK Göteborg',
 '\n\n\n\nFC Cartagena',
 '\n\n\n\nSanta Clara',
 '\n\n\n\nFC Twente',
 '\n\n\n\nFarense',
 '\n\n\n\nADO Den Haag',
 '\n\n\n\nAJ Auxerre',
 '\n\n\n\nAl Fateh',
 '\n\n\n\nValenciennes FC',
 '\n\n\n\nHokkaido Consadole Sapporo',
 '\n\n\n\nFC St. Pauli',
 '\n\n\n\nAlbacete BP',
 '\n\n\n\n1. FC Kaiserslautern',
 '\n\n\n\nAl Fayha',
 '\n\n\n\nIncheon United FC',
 '\n\n\n\nKV Mechelen',
 '\n\n\n\nPohang Steelers',
 '\n\n\n\nCD Nacional',
 '\n\n\n\nUnión La Calera',
 '\n\n\n\nBB Erzurumspor',
 '\n\n\n\nKashima Antlers',
 '\n\n\n\nArsenal de Sarandí',
 '\n\n\n\nHJK Helsinki',
 '\n\n\n\nKarlsruher SC',
 '\n\n\n\nAarhus GF',
 '\n\n\n\nFC Zürich',
 '\n\n\n\nBarcelona Sporting Club',
 '\n\n\n\nSG Dynamo Dresden',
 '\n\n\n\nSanfrecce Hiroshima',
 '\n\n\n\nAl Raed',
 '\n\n\n\nSD Ponferradina',
 '\n\n\n\nBrøndby IF',
 '\n\n\n\nLechia Gdańsk',
 '\n\n\n\nFC Viitorul',
 '\n\n\n\nSK Sturm Graz',
 '\n\n\n\nIF Elfsborg',
 '\n\n\n\nGangwon FC',
 '\n\n\n\nMelgar FBC',
 '\n\n\n\nClub Atlético Grau',
 '\n\n\n\nJagiellonia Białystok',
 '\n\n\n\nWaasland-Beveren',
 '\n\n\n\nVfL Osnabrück',
 '\n\n\n\nNagoya Grampus',
 '\n\n\n\nCF Fuenlabrada',
 '\n\n\n\nShamrock Rovers',
 '\n\n\n\nShimizu S-Pulse',
 '\n\n\n\nRKC Waalwijk',
 '\n\n\n\nVålerenga Fotball',
 '\n\n\n\nClermont Foot 63',
 '\n\n\n\nFC Ingolstadt 04',
 '\n\n\n\nFC Würzburger Kickers',
 '\n\n\n\nGórnik Zabrze',
 '\n\n\n\nCharlton Athletic',
 '\n\n\n\nBeerschot AC',
 '\n\n\n\nCoquimbo Unido',
 '\n\n\n\nViktoria Köln',
 '\n\n\n\nHull City',
 '\n\n\n\nMálaga CF',
 '\n\n\n\nFC Nordsjælland',
 '\n\n\n\nUD Las Palmas',
 '\n\n\n\nVVV-Venlo',
 '\n\n\n\nGwangJu FC',
 '\n\n\n\nChamois Niortais Football Club',
 '\n\n\n\nFC Lugano',
 '\n\n\n\nCusco FC',
 '\n\n\n\nSparta Rotterdam',
 '\n\n\n\nSol de América',
 '\n\n\n\nPEC Zwolle',
 '\n\n\n\nPogoń Szczecin',
 '\n\n\n\nDoncaster Rovers',
 '\n\n\n\nKristiansund BK',
 '\n\n\n\nLiverpool Fútbol Club',
 '\n\n\n\nClub Bolívar',
 '\n\n\n\nUrawa Red Diamonds',
 '\n\n\n\nSK Brann',
 '\n\n\n\nEintracht Braunschweig',
 '\n\n\n\nNacional Asunción',
 '\n\n\n\nMelbourne Victory',
 '\n\n\n\nKilmarnock',
 '\n\n\n\nDundalk',
 '\n\n\n\nSSV Jahn Regensburg',
 '\n\n\n\nAbha Club',
 '\n\n\n\nClub Atlético Tigre',
 '\n\n\n\nSuwon Samsung Bluewings',
 '\n\n\n\nShonan Bellmare',
 '\n\n\n\nSD Aucas',
 '\n\n\n\nEmelec',
 '\n\n\n\nFortuna Sittard',
 '\n\n\n\nLa Berrichonne de Châteauroux',
 '\n\n\n\nŚląsk Wrocław',
 '\n\n\n\nCoventry City',
 '\n\n\n\nSunderland',
 '\n\n\n\nAlianza Lima',
 '\n\n\n\nHammarby IF',
 '\n\n\n\nCracovia',
 '\n\n\n\nCE Sabadell FC',
 '\n\n\n\nOita Trinita',
 '\n\n\n\nBK Häcken',
 '\n\n\n\nLuton Town',
 '\n\n\n\nLe Havre AC',
 '\n\n\n\nIK Sirius',
 '\n\n\n\nZagłębie Lubin',
 '\n\n\n\nGrenoble Foot 38',
 '\n\n\n\nMacarthur FC',
 '\n\n\n\nRodez Aveyron Football',
 '\n\n\n\nVegalta Sendai',
 '\n\n\n\nMotherwell',
 '\n\n\n\nSV Wehen Wiesbaden',
 '\n\n\n\nAudax Italiano',
 '\n\n\n\nGaz Metan Mediaş',
 '\n\n\n\nPortsmouth',
 '\n\n\n\nHibernian',
 '\n\n\n\nAlways Ready',
 '\n\n\n\nUD Logroñés',
 '\n\n\n\nFC Voluntari',
 '\n\n\n\nFC Hermannstadt',
 '\n\n\n\nAS Nancy Lorraine',
 '\n\n\n\nRotherham United',
 '\n\n\n\nFleetwood Town',
 '\n\n\n\nJorge Wilstermann',
 '\n\n\n\nOdense Boldklub',
 '\n\n\n\nMSV Duisburg',
 '\n\n\n\nFC Sochaux-Montbéliard',
 '\n\n\n\nMilton Keynes Dons',
 '\n\n\n\nRiver Plate Montevideo',
 '\n\n\n\nDelfín SC',
 '\n\n\n\nUniversidad Católica del Ecuador',
 '\n\n\n\nDeportivo Pasto',
 '\n\n\n\nKV Oostende',
 '\n\n\n\nClub Plaza Colonia',
 '\n\n\n\nWigan Athletic',
 '\n\n\n\nFC Botoşani',
 '\n\n\n\nC.D. Castellón',
 '\n\n\n\nSCR Altach',
 '\n\n\n\nÖrebro SK',
 '\n\n\n\nTSV Hartberg',
 '\n\n\n\nStabæk Fotball',
 '\n\n\n\nWycombe Wanderers',
 '\n\n\n\nSt. Johnstone FC',
 '\n\n\n\nOxford United',
 '\n\n\n\nLincoln City',
 '\n\n\n\nRanders FC',
 '\n\n\n\nViking FK',
 '\n\n\n\nFC Chambly Oise',
 '\n\n\n\nDundee United',
 '\n\n\n\nOriente Petrolero',
 '\n\n\n\nOdds BK',
 '\n\n\n\nNacional Potosí',
 '\n\n\n\nSepsi OSK',
 '\n\n\n\nFC Hansa Rostock',
 '\n\n\n\nLyngby BK',
 '\n\n\n\nSpVgg Unterhaching',
 '\n\n\n\nBrisbane Roar',
 '\n\n\n\nSeongnam FC',
 '\n\n\n\nSV Ried',
 '\n\n\n\nCD Huachipato',
 '\n\n\n\nWSG Tirol',
 '\n\n\n\nPodbeskidzie Bielsko-Biała',
 '\n\n\n\nPeterborough United',
 '\n\n\n\nClub Blooming',
 '\n\n\n\nWisła Płock',
 '\n\n\n\nBusan IPark',
 '\n\n\n\nFSV Zwickau',
 '\n\n\n\nMjøndalen IF',
 '\n\n\n\nVejle Boldklub',
 '\n\n\n\nPau FC',
 '\n\n\n\nFC Lausanne-Sport',
 '\n\n\n\nEstudiantes de Mérida',
 '\n\n\n\nSagan Tosu',
 '\n\n\n\nSV Waldhof Mannheim',
 '\n\n\n\nSport Huancayo',
 '\n\n\n\nHallescher FC',
 '\n\n\n\nKalmar FF',
 '\n\n\n\nSt. Mirren',
 '\n\n\n\nSKN St. Pölten',
 '\n\n\n\nSarpsborg 08 FF',
 '\n\n\n\nShrewsbury',
 '\n\n\n\nTSV 1860 München',
 '\n\n\n\nSV Meppen',
 '\n\n\n\nIpswich Town',
 '\n\n\n\nIK Start',
 '\n\n\n\nAdelaide United',
 '\n\n\n\nStal Mielec',
 '\n\n\n\nCentro Atlético Fénix',
 '\n\n\n\nNewcastle Jets',
 '\n\n\n\nLivingston FC',
 '\n\n\n\nAC Mineros de Guayana',
 '\n\n\n\nAFC Wimbledon',
 '\n\n\n\nBurton Albion',
 '\n\n\n\nAl Adalah',
 '\n\n\n\nWarta Poznań',
 '\n\n\n\nUSL Dunkerque',
 '\n\n\n\nBristol Rovers',
 '\n\n\n\nUTA Arad',
 '\n\n\n\nÖstersunds FK',
 '\n\n\n\nSportivo Luqueño',
 '\n\n\n\nPolitehnica Iaşi',
 '\n\n\n\nSalford City',
 '\n\n\n\nCentral Coast Mariners',
 '\n\n\n\nCaracas FC',
 '\n\n\n\nAC Horsens',
 '\n\n\n\nPlymouth Argyle',
 '\n\n\n\nAalesunds FK',
 '\n\n\n\nCrewe Alexandra',
 '\n\n\n\nChindia Târgovişte',
 '\n\n\n\nOldham Athletic',
 '\n\n\n\nYokohama FC',
 '\n\n\n\nBlackpool',
 '\n\n\n\nNorthampton Town',
 '\n\n\n\nBayern München II',
 '\n\n\n\nFK Haugesund',
 '\n\n\n\nKFC Uerdingen 05',
 '\n\n\n\nForest Green Rovers',
 '\n\n\n\nCheltenham Town',
 '\n\n\n\nStrømsgodset IF',
 '\n\n\n\nMjällby AIF',
 '\n\n\n\nExeter City',
 '\n\n\n\nCambridge United',
 '\n\n\n\nGrimsby Town',
 '\n\n\n\nFC Vaduz',
 '\n\n\n\nTürkgücü München',
 '\n\n\n\nVfB Lübeck',
 '\n\n\n\nBolton Wanderers',
 '\n\n\n\nBradford City',
 '\n\n\n\n1. FC Magdeburg',
 '\n\n\n\nFC Admira Wacker Mödling',
 '\n\n\n\nHamilton Academical FC',
 '\n\n\n\nAragua FC',
 '\n\n\n\nAccrington Stanley',
 '\n\n\n\nSwindon Town',
 '\n\n\n\nCarlisle United',
 '\n\n\n\nFC Argeș',
 '\n\n\n\nPort Vale',
 '\n\n\n\nAcademica Clinceni',
 '\n\n\n\nRochdale',
 '\n\n\n\nGillingham',
 '\n\n\n\nTranmere Rovers',
 '\n\n\n\nSouthend United',
 '\n\n\n\n1. FC Saarbrücken',
 '\n\n\n\nColchester United',
 '\n\n\n\nMansfield Town',
 '\n\n\n\nFalkenbergs FF',
 '\n\n\n\nSC Verl',
 '\n\n\n\nVarbergs BoIS',
 '\n\n\n\nCrawley Town',
 '\n\n\n\nSandefjord Fotball',
 '\n\n\n\nNewport County',
 '\n\n\n\nBohemian FC',
 '\n\n\n\nRoss County FC',
 '\n\n\n\nScunthorpe United',
 '\n\n\n\nMorecambe',
 '\n\n\n\nWalsall',
 '\n\n\n\nLeyton Orient',
 '\n\n\n\nStevenage',
 '\n\n\n\nBarrow',
 '\n\n\n\nDerry City',
 '\n\n\n\nLlaneros de Guanare',
 '\n\n\n\nSligo Rovers',
 '\n\n\n\nZamora FC',
 "\n\n\n\nSt. Patrick's Athletic",
 '\n\n\n\nCork City',
 '\n\n\n\nShelbourne FC',
 '\n\n\n\nHarrogate Town',
 '\n\n\n\nWaterford FC',
 '\n\n\n\nFinn Harps']

In [36]:
df['Contract'].unique().tolist()

['2004 ~ 2021',
 '2018 ~ 2022',
 '2014 ~ 2023',
 '2015 ~ 2023',
 '2017 ~ 2022',
 '2017 ~ 2023',
 '2018 ~ 2024',
 '2014 ~ 2022',
 '2018 ~ 2023',
 '2016 ~ 2023',
 '2013 ~ 2023',
 '2011 ~ 2023',
 '2009 ~ 2022',
 '2005 ~ 2021',
 '2011 ~ 2021',
 '2015 ~ 2022',
 '2017 ~ 2024',
 '2010 ~ 2024',
 '2012 ~ 2021',
 '2019 ~ 2024',
 '2015 ~ 2024',
 '2017 ~ 2025',
 '2020 ~ 2025',
 '2019 ~ 2023',
 '2008 ~ 2023',
 '2015 ~ 2021',
 '2020 ~ 2022',
 '2012 ~ 2022',
 '2016 ~ 2025',
 '2013 ~ 2022',
 '2011 ~ 2022',
 '2012 ~ 2024',
 '2016 ~ 2021',
 '2012 ~ 2023',
 '2008 ~ 2022',
 '2019 ~ 2022',
 '2017 ~ 2021',
 '2013 ~ 2024',
 '2020 ~ 2024',
 '2010 ~ 2022',
 '2020 ~ 2021',
 '2011 ~ 2024',
 '2020 ~ 2023',
 '2014 ~ 2024',
 '2013 ~ 2026',
 '2016 ~ 2022',
 '2010 ~ 2021',
 '2013 ~ 2021',
 '2019 ~ 2025',
 '2018 ~ 2025',
 '2016 ~ 2024',
 '2018 ~ 2021',
 '2009 ~ 2024',
 '2007 ~ 2022',
 'Jun 30, 2021 On Loan',
 '2009 ~ 2021',
 '2019 ~ 2021',
 '2019 ~ 2026',
 'Free',
 '2012 ~ 2028',
 '2010 ~ 2023',
 '2014 ~ 2021',
 '2015 ~ 2025',
 '2014 ~ 2026',
 '2012 ~ 2025',
 '2017 ~ 2020',
 '2002 ~ 2022',
 '2020 ~ 2027',
 '2013 ~ 2025',
 'Dec 31, 2020 On Loan',
 '2019 ~ 2020',
 '2011 ~ 2025',
 '2016 ~ 2020',
 '2007 ~ 2021',
 '2020 ~ 2026',
 '2010 ~ 2025',
 '2009 ~ 2023',
 '2008 ~ 2021',
 '2020 ~ 2020',
 '2016 ~ 2026',
 'Jan 30, 2021 On Loan',
 '2012 ~ 2020',
 '2014 ~ 2025',
 'Jun 30, 2022 On Loan',
 '2015 ~ 2020',
 'May 31, 2021 On Loan',
 '2018 ~ 2020',
 '2014 ~ 2020',
 '2013 ~ 2020',
 '2006 ~ 2024',
 'Jul 5, 2021 On Loan',
 'Dec 31, 2021 On Loan',
 '2004 ~ 2025',
 '2011 ~ 2020',
 'Jul 1, 2021 On Loan',
 'Jan 1, 2021 On Loan',
 '2006 ~ 2023',
 'Aug 31, 2021 On Loan',
 '2006 ~ 2021',
 '2005 ~ 2023',
 '2003 ~ 2020',
 '2009 ~ 2020',
 '2002 ~ 2020',
 '2005 ~ 2020',
 '2005 ~ 2022',
 'Jan 31, 2021 On Loan',
 '2010 ~ 2020',
 'Dec 30, 2021 On Loan',
 '2008 ~ 2020',
 '2007 ~ 2020',
 '2003 ~ 2021',
 'Jun 23, 2021 On Loan',
 'Jan 3, 2021 On Loan',
 'Nov 27, 2021 On Loan',
 '2002 ~ 2021',
 'Jan 17, 2021 On Loan',
 'Jun 30, 2023 On Loan',
 '1998 ~ 2021',
 '2003 ~ 2022',
 '2007 ~ 2023',
 'Jul 31, 2021 On Loan',
 'Nov 22, 2020 On Loan',
 'May 31, 2022 On Loan',
 '2006 ~ 2020',
 'Dec 30, 2020 On Loan',
 '2007 ~ 2025',
 'Jan 4, 2021 On Loan',
 'Nov 30, 2020 On Loan',
 '2004 ~ 2020',
 '2009 ~ 2025',
 'Aug 1, 2021 On Loan']

In [37]:
df['Positions'].unique().tolist()

['RW, ST, CF',
 'ST, LW',
 'GK',
 'CAM, CM',
 'LW, CAM',
 'ST',
 'RW',
 'ST, LW, RW',
 'CB',
 'LW',
 'CDM',
 'CF, ST',
 'LW, RW',
 'CDM, CM',
 'CDM, RB',
 'CF, CAM',
 'LW, ST',
 'CM',
 'ST, CF, LW',
 'RM, LM, CAM',
 'RB',
 'RW, CAM, CM',
 'LB',
 'LM, CF',
 'CF',
 'RW, LW',
 'CAM, RM, RW',
 'CM, CDM',
 'CAM, CF, ST',
 'CM, CDM, CAM',
 'CF, LW, CAM',
 'CAM, RM, CF',
 'LM, ST',
 'RM, LM, RW',
 'LM',
 'CAM, RW',
 'CB, CDM',
 'RW, RM',
 'LW, CF',
 'CM, RM, LM',
 'LB, LM',
 'CAM, CM, RM',
 'CAM, CM, CF',
 'CAM, CF',
 'LM, RM, LW',
 'LM, LB, CM',
 'CM, LM, LB',
 'RM, RW',
 'RM, CM',
 'CAM, CM, LW',
 'CB, LB',
 'RM, RB',
 'ST, RW',
 'LM, RW, LW',
 'RB, LB',
 'RB, RM',
 'RM',
 'LM, RM, CF',
 'CAM, RM',
 'RB, RWB',
 'CDM, CB, CM',
 'CAM, RM, ST',
 'LM, LW, RM',
 'CM, CAM',
 'ST, RM, CF',
 'LM, RM',
 'RM, CF',
 'LM, LWB',
 'RW, RM, CF',
 'RB, CM',
 'LW, CAM, RW',
 'CAM, LW, CM',
 'CM, CAM, CDM',
 'RW, LW, CAM',
 'CM, CAM, LM',
 'CM, RM, ST',
 'CDM, CM, RB',
 'ST, CAM',
 'CAM, LW, ST',
 'LB, CB, LWB',
 'RM, ST',
 'CB, CDM, LB',
 'RWB, RM',
 'CM, LM, RM',
 'RB, CDM, CM',
 'RW, LW, RM',
 'LM, LW',
 'CM, LM',
 'LM, LB',
 'RM, LM, CF',
 'LB, LM, RM',
 'CDM, CM, CAM',
 'ST, LW, RM',
 'CAM, CM, ST',
 'ST, CF',
 'LWB, LB',
 'LW, RW, LM',
 'RM, RW, ST',
 'LWB',
 'CF, ST, CAM',
 'LM, CAM, RM',
 'RB, CB',
 'ST, LM',
 'RW, CAM',
 'LM, CAM',
 'RWB, RB',
 'ST, RW, LW',
 'CAM',
 'RB, RM, RW',
 'LB, LWB',
 'RM, CAM',
 'CAM, ST',
 'CDM, CB',
 'CF, LM, LW',
 'CAM, LM, LW',
 'LW, RW, CAM',
 'CB, RB',
 'RB, CB, RWB',
 'LM, LW, ST',
 'LW, ST, CM',
 'RM, CAM, CM',
 'CB, RB, RWB',
 'RW, ST, LW',
 'LW, CAM, CM',
 'CM, LM, CDM',
 'LB, LM, LWB',
 'CB, LB, RB',
 'CAM, LW',
 'RWB, RB, RM',
 'CF, CAM, ST',
 'RM, CAM, RW',
 'RW, ST',
 'LW, LM',
 'RB, RM, CM',
 'ST, CAM, RW',
 'CM, RB, LB',
 'CAM, LM, RM',
 'RB, RW',
 'LM, CM',
 'RM, LM, CM',
 'CDM, CM, CB',
 'CM, CF',
 'CF, LW, RW',
 'ST, RM',
 'CAM, CM, CDM',
 'LB, CB',
 'RW, RWB',
 'ST, LM, RM',
 'RM, RWB, RB',
 'LM, ST, CAM',
 'CAM, ST, CF',
 'LW, CM',
 'RB, RWB, LB',
 'RM, LM',
 'CM, CAM, RM',
 'ST, LW, CAM',
 'RM, RW, CAM',
 'CM, CDM, RM',
 'RB, RM, RWB',
 'CDM, CB, LB',
 'CAM, ST, LM',
 'LM, CM, RM',
 'CF, RW',
 'CAM, RM, LW',
 'CM, RM, CDM',
 'LB, LWB, LM',
 'LW, RW, CF',
 'LW, LM, CAM',
 'LWB, LW, LB',
 'CDM, CM, LM',
 'CB, CM',
 'RWB, RW, RB',
 'ST, RW, RM',
 'LW, RW, CM',
 'LM, RM, CAM',
 'LB, RB',
 'RWB, RM, RB',
 'LM, RB, LB',
 'LW, LM, ST',
 'ST, RM, LM',
 'CAM, CM, LM',
 'CF, CM',
 'LW, ST, RW',
 'ST, CAM, CF',
 'LB, CB, LM',
 'CM, CDM, LM',
 'RM, RWB',
 'LB, LM, RB',
 'RB, LB, CB',
 'CM, CDM, RB',
 'LB, CM',
 'CF, CAM, LW',
 'RM, LWB',
 'CF, ST, LM',
 'LB, RB, CB',
 'LW, CF, ST',
 'RM, ST, CAM',
 'LW, RW, ST',
 'ST, LW, LM',
 'CM, LW',
 'CDM, CM, LB',
 'CM, RM, CAM',
 'ST, CF, CAM',
 'CM, LM, CAM',
 'RWB',
 'LM, ST, RM',
 'CAM, RM, CM',
 'CAM, LM, CM',
 'RW, LW, ST',
 'CAM, RM, LM',
 'CF, ST, LW',
 'LWB, LB, LM',
 'RM, CM, CAM',
 'LB, LM, CAM',
 'CAM, CDM',
 'RW, RB, RM',
 'RM, ST, RW',
 'CM, CAM, LW',
 'CF, ST, RW',
 'LM, RM, RB',
 'LM, RM, CM',
 'CB, RB, RM',
 'RB, CDM',
 'RM, ST, LM',
 'LB, LWB, CB',
 'CDM, LB',
 'LM, RM, ST',
 'RWB, RB, LWB',
 'ST, LM, CAM',
 'ST, RM, CAM',
 'RB, RWB, RM',
 'CF, LM, CAM',
 'CAM, CF, RW',
 'RB, RM, LB',
 'CDM, RWB',
 'CM, RW, CAM',
 'ST, CF, LM',
 'RM, LM, RWB',
 'RB, LB, RM',
 'LM, LW, LB',
 'RM, LM, ST',
 'CAM, LM',
 'ST, LM, LW',
 'LW, RW, RM',
 'CF, LW',
 'LB, CM, RB',
 'RB, CB, CDM',
 'CB, RB, LB',
 'CAM, RW, RM',
 'LWB, LM',
 'LW, CF, LM',
 'CAM, CF, CM',
 'LWB, CB',
 'CM, CDM, LW',
 'LM, CM, LB',
 'CM, RM',
 'RW, LW, CF',
 'CM, CDM, CB',
 'LM, RM, RW',
 'RM, RW, LM',
 'RM, CAM, LM',
 'LWB, RM, LB',
 'RM, LB, RB',
 'CM, CF, RM',
 'RM, RB, LB',
 'ST, LM, RW',
 'CAM, ST, LW',
 'CF, LW, ST',
 'LM, LW, CAM',
 'RM, RW, CF',
 'LW, LM, CF',
 'CM, RW, LW',
 'LM, CM, CAM',
 'CAM, RW, ST',
 'CM, CAM, CF',
 'RW, LWB, LW',
 'CB, RB, CDM',
 'RW, RM, LW',
 'LW, ST, LM',
 'RWB, RW',
 'ST, CAM, LM',
 'CM, CB',
 'RM, RW, CM',
 'LWB, CM',
 'RM, LM, LB',
 'RM, CAM, ST',
 'CDM, RM, RB',
 'LM, LB, RB',
 'LB, RB, RWB',
 'RM, RWB, CAM',
 'CAM, LM, CF',
 'LM, CAM, CM',
 'CF, CAM, RW',
 'CDM, CM, RM',
 'CF, CAM, CM',
 'ST, RM, LW',
 'CB, CDM, CM',
 'RB, RW, LB',
 'ST, RW, CAM',
 'CM, LB',
 'LW, RM, RW',
 'CM, RM, RW',
 'RM, CF, LM',
 'CF, LM, RM',
 'CAM, ST, RM',
 'RW, CF',
 'CM, CAM, ST',
 'CAM, CDM, CM',
 'RM, RW, LW',
 'CAM, LM, LB',
 'CAM, RW, LW',
 'CDM, CAM',
 'LWB, LM, LB',
 'RW, LB',
 'LW, CAM, CF',
 'RB, RWB, CB',
 'LM, CF, RM',
 'RB, LB, RWB',
 'RM, LW',
 'CAM, LM, ST',
 'LW, LM, LB',
 'LB, RB, RM',
 'CM, LWB',
 'CDM, RB, RM',
 'RM, CM, RB',
 'ST, RM, RW',
 'LM, RM, LWB',
 'RW, LW, LM',
 'LW, CF, RW',
 'CM, CDM, LB',
 'ST, LM, RB',
 'LB, CDM',
 'CM, CB, CDM',
 'CB, LB, CDM',
 'RW, ST, RM',
 'RM, ST, CF',
 'CAM, LW, LM',
 'LM, ST, LW',
 'CAM, RM, RB',
 'RB, CM, RM',
 'CM, LW, LM',
 'ST, CAM, RM',
 'RW, ST, CAM',
 'CM, LB, LM',
 'RB, CDM, RM',
 'LM, RWB, RM',
 'LM, CAM, LB',
 'CAM, LW, RW',
 'CM, RM, RWB',
 'RW, CAM, LW',
 'RB, CB, LB',
 'LB, LM, LW',
 'RW, RB',
 'LM, LWB, CM',
 'RM, CAM, RB',
 'RM, CM, ST',
 'RB, RM, LM',
 'LM, LB, LW',
 'LM, ST, CF',
 'RW, LWB, RM',
 'LM, CAM, LW',
 'CB, RWB',
 'RM, LW, CAM',
 'LB, LW',
 'CDM, CM, ST',
 'LB, CM, CDM',
 'CF, CAM, LM',
 'RW, CAM, RM',
 'RW, LM, LW',
 'RW, CM, CAM',
 'LM, LW, RW',
 'RM, LW, RW',
 'LW, LWB, RWB',
 'RM, LM, RB',
 'CB, CDM, RB',
 'CAM, RW, CM',
 'ST, CAM, CM',
 'LWB, LM, CM',
 'RW, LW, RWB',
 'CB, LB, LWB',
 'CM, LM, ST',
 'CM, LWB, LM',
 'LB, LW, LM',
 'RB, CM, CAM',
 'RM, CAM, CF',
 'CM, RW',
 'RW, RM, CAM',
 'CB, LWB',
 'CAM, RB',
 'LM, CM, CDM',
 'RM, LB, LM',
 'CB, RB, CM',
 'RB, CM, RWB',
 'LB, RB, LM',
 'CAM, ST, RW',
 'LB, LW, RW',
 'CDM, CAM, CM',
 'CAM, ST, CM',
 'LM, CAM, ST',
 'LM, ST, CM',
 'CAM, CF, RM',
 'CF, ST, RM',
 'LM, ST, LB',
 'ST, CAM, LW',
 'LWB, CM, LB',
 'RWB, RM, LWB',
 'LWB, LM, RB',
 'CM, LW, ST',
 'LB, LM, CB',
 'CM, RM, RB',
 'RWB, CB',
 'RM, RB, RWB',
 'LB, CM, LM',
 'ST, LW, CF',
 'RM, RWB, ST',
 'CF, ST, CM',
 'LM, LB, LWB',
 'LM, RW',
 'LM, LWB, LB',
 'LB, LWB, RB',
 'RM, RB, LM',
 'RM, CM, LM',
 'LW, ST, CAM',
 'RB, RM, CB',
 'LWB, RWB, LB',
 'CF, RM, RW',
 'RM, CF, CAM',
 'LM, LW, CF',
 'RB, LM, LB',
 'CAM, CM, RW',
 'LB, CM, LW',
 'CM, CF, CAM',
 'RW, RM, ST',
 'CDM, RB, CM',
 'CM, RB',
 'RB, RWB, RW',
 'LM, RW, RM',
 'CM, RB, CDM',
 'LM, RM, LB',
 'CDM, RB, CB',
 'RB, CB, RM',
 'RWB, LW, LM',
 'ST, CF, RW',
 'RM, CM, CDM',
 'LM, CF, ST',
 'LW, CAM, LM',
 'CDM, LM, CM',
 'ST, CM, CAM',
 'LM, RM, RWB',
 'CM, CAM, RW',
 'CAM, LM, RW',
 'LW, LM, RM',
 'CAM, RW, CF',
 'LM, ST, RW',
 'CB, LWB, LB',
 'RW, CF, LW',
 'CB, CM, CDM',
 'CB, CAM',
 'LW, LB',
 'CDM, RB, LB',
 'ST, CM, RB',
 'RWB, LWB, RB',
 'CM, CB, RB',
 'LB, LW, RB',
 'CF, RM, RWB',
 'LB, RM',
 'RM, RW, RB',
 'LB, RM, RB',
 'CDM, RM, CM',
 'CDM, LB, CM',
 'LM, CDM, CM',
 'RW, LM, CAM',
 'LM, LB, RM',
 'RM, CF, ST',
 'RW, CM',
 'RM, RWB, LM',
 'CF, CM, ST',
 'RW, RM, LM',
 'LM, CM, RW',
 'RWB, CM',
 'RB, RM, CDM',
 'CM, CB, CAM',
 'CF, CM, LM',
 'RWB, LWB, RM',
 'CF, RM',
 'CM, CF, ST',
 'RWB, RB, CB',
 'LWB, RWB',
 'RM, LM, LW',
 'LW, RM, CM',
 'LW, CAM, ST',
 'ST, RM, RWB',
 'ST, CM',
 'CDM, CM, RWB',
 'LB, CB, RB',
 'CB, ST, CAM',
 'CF, RM, CM',
 'CDM, CB, RB',
 'CM, LM, RB',
 'RB, CB, LWB',
 'LM, LB, CDM',
 'LW, LWB',
 'RW, CF, CAM',
 'RM, RB, CAM',
 'LB, RB, CM',
 'RM, CDM, LM',
 'LWB, LB, CB',
 'LB, RB, CDM',
 'RB, CM, LB',
 'CDM, RM',
 'LM, RB, CB',
 'RW, RWB, RM',
 'RM, LW, ST',
 'LB, RB, LWB',
 'RM, LM, CDM',
 'RB, RM, CAM',
 'RM, ST, LW',
 'CF, LM',
 'RB, LB, CDM',
 'RW, LW, RB',
 'RB, RWB, CDM',
 'CM, CAM, LB',
 'LW, RW, LWB',
 'CB, LWB, RWB',
 'LB, CB, CDM',
 'ST, RB, RM',
 'CM, RB, RM',
 'RW, LM',
 'RM, CF, RB',
 'CB, RM, RB',
 'RWB, LWB',
 'CM, ST, CDM',
 'LWB, LW',
 'CB, RB, ST',
 'LB, LWB, CDM',
 'CB, RWB, RM',
 'CB, ST',
 'CM, ST',
 'LM, LWB, CB',
 'ST, LW, LWB',
 'LM, CDM, RM',
 'LWB, LB, RW',
 'RB, CM, CB',
 'LM, RW, ST',
 'CM, RM, LW',
 'ST, RW, LM',
 'RWB, CM, RM',
 'CAM, RWB, CM',
 'CM, RB, LM',
 'RM, RB, RW',
 'LW, LM, CM',
 'RM, LM, LWB',
 'ST, LM, CF',
 'LW, RM, CAM',
 'RB, RWB, LWB',
 'LB, CM, ST',
 'ST, LWB',
 'RB, ST, LM',
 'CDM, CAM, LM',
 'LM, ST, LWB',
 'LB, RB, RW',
 'RM, CDM',
 'RB, LB, LWB',
 'RW, CAM, LM',
 'LB, CDM, LM',
 'RW, RB, LM',
 'CB, LM',
 'RW, LM, RM',
 'RM, LB, CM',
 'LW, CAM, RM',
 'RW, RB, LB',
 'LW, LB, LM',
 'CDM, RB, RWB',
 'CB, RW',
 'CM, LM, LW',
 'LM, RM, CB',
 'LM, LWB, ST',
 'ST, CB, CDM',
 'LB, CDM, CB',
 'CDM, CB, RM',
 'RB, RWB, CM',
 'ST, RW, CF',
 'ST, CB',
 'ST, LW, CM',
 'LM, LB, ST',
 'ST, CB, RB',
 'RB, LM',
 'GK, RB',
 'LM, LW, CM',
 'LM, CM, LW',
 'CB, CAM, CM',
 'LM, RB',
 'RWB, CAM',
 'RB, CAM',
 'CB, CDM, RM',
 'ST, RB',
 'ST, RWB',
 'CAM, CDM, LM',
 'CB, RWB, RB',
 'LM, LWB, RM',
 'LB, LM, CM',
 'CM, CF, LM',
 'CM, RWB',
 'CDM, LM',
 'ST, CF, RM',
 'CAM, LB',
 'RB, RM, ST',
 'LM, CDM',
 'CDM, RW, RB',
 'LM, CF, CAM',
 'LWB, LM, RWB',
 'CF, RM, ST',
 'CAM, CF, LM',
 'RB, ST, CB',
 'RW, RB, LW',
 'LB, LM, CDM',
 'RB, CB, ST',
 'RWB, CB, RB',
 'CDM, ST',
 'LW, RM, LM',
 'RB, LWB',
 'CDM, LB, CB',
 'LM, LB, CF',
 'RB, CDM, LB',
 'LB, LWB, CM',
 'RM, LM, CB',
 'CAM, LW, CF',
 'LB, LW, CM',
 'RB, CM, CDM',
 'LWB, LM, ST',
 'CM, RW, RM',
 'CB, RM',
 'CM, LM, CB',
 'LM, LB, CB',
 'ST, RW, CM',
 'RM, ST, CM',
 'RWB, RM, LM',
 'CM, CAM, RB',
 'CM, RWB, CDM',
 'LB, LWB, LW']

In [38]:
df['Positions'].str.split(',').str.len().max()

np.int64(3)

In [39]:
df['Height'].unique().tolist()

['170cm',
 '187cm',
 '188cm',
 '181cm',
 '175cm',
 '184cm',
 '191cm',
 '178cm',
 '193cm',
 '185cm',
 '199cm',
 '173cm',
 '168cm',
 '176cm',
 '177cm',
 '183cm',
 '180cm',
 '189cm',
 '179cm',
 '195cm',
 '172cm',
 '182cm',
 '186cm',
 '192cm',
 '165cm',
 '194cm',
 '167cm',
 '196cm',
 '163cm',
 '190cm',
 '174cm',
 '169cm',
 '171cm',
 '197cm',
 '200cm',
 '166cm',
 '6\'2"',
 '164cm',
 '198cm',
 '6\'3"',
 '6\'5"',
 '5\'11"',
 '6\'4"',
 '6\'1"',
 '6\'0"',
 '5\'10"',
 '5\'9"',
 '5\'6"',
 '5\'7"',
 '5\'4"',
 '201cm',
 '158cm',
 '162cm',
 '161cm',
 '160cm',
 '203cm',
 '157cm',
 '156cm',
 '202cm',
 '159cm',
 '206cm',
 '155cm']

In [40]:
df['Weight'].unique().tolist()

['72kg',
 '83kg',
 '87kg',
 '70kg',
 '68kg',
 '80kg',
 '71kg',
 '91kg',
 '73kg',
 '85kg',
 '92kg',
 '69kg',
 '84kg',
 '96kg',
 '81kg',
 '82kg',
 '75kg',
 '86kg',
 '89kg',
 '74kg',
 '76kg',
 '64kg',
 '78kg',
 '90kg',
 '66kg',
 '60kg',
 '94kg',
 '79kg',
 '67kg',
 '65kg',
 '59kg',
 '61kg',
 '93kg',
 '88kg',
 '97kg',
 '77kg',
 '62kg',
 '63kg',
 '95kg',
 '100kg',
 '58kg',
 '183lbs',
 '179lbs',
 '172lbs',
 '196lbs',
 '176lbs',
 '185lbs',
 '170lbs',
 '203lbs',
 '168lbs',
 '161lbs',
 '146lbs',
 '130lbs',
 '190lbs',
 '174lbs',
 '148lbs',
 '165lbs',
 '159lbs',
 '192lbs',
 '181lbs',
 '139lbs',
 '154lbs',
 '157lbs',
 '163lbs',
 '98kg',
 '103kg',
 '99kg',
 '102kg',
 '56kg',
 '101kg',
 '57kg',
 '55kg',
 '104kg',
 '107kg',
 '110kg',
 '53kg',
 '50kg',
 '54kg',
 '52kg']

In [41]:
df['Preferred Foot'].unique().tolist()

['Left', 'Right']

In [42]:
df['BOV'].unique().tolist()

[93,
 92,
 91,
 90,
 89,
 88,
 87,
 86,
 85,
 84,
 83,
 82,
 81,
 80,
 79,
 78,
 77,
 76,
 75,
 74,
 73,
 72,
 71,
 70,
 69,
 68,
 67,
 66,
 65,
 64,
 63,
 62,
 61,
 60,
 59,
 58,
 57,
 56,
 55,
 54,
 53,
 52,
 51,
 50,
 49,
 48]

In [44]:
df['Joined'].unique().tolist()

['Jul 1, 2004',
 'Jul 10, 2018',
 'Jul 16, 2014',
 'Aug 30, 2015',
 'Aug 3, 2017',
 'Jul 1, 2014',
 'Jul 1, 2017',
 'Jul 19, 2018',
 'Jul 1, 2018',
 'Jan 1, 2018',
 'Jul 1, 2016',
 'Jul 11, 2013',
 'Aug 9, 2018',
 'Jul 1, 2011',
 'Jul 9, 2009',
 'Aug 1, 2005',
 'Jul 28, 2011',
 'Jul 14, 2015',
 'Jul 16, 2016',
 'Jul 1, 2015',
 'Jul 1, 2010',
 'Jul 1, 2012',
 'Jul 1, 2019',
 'Jul 17, 2014',
 'Jul 12, 2019',
 'Aug 31, 2017',
 'Oct 7, 2015',
 'Jul 21, 2017',
 'Jan 30, 2018',
 'Jan 30, 2020',
 'Aug 28, 2015',
 'Jul 6, 2015',
 'Sep 2, 2019',
 'Jul 1, 2005',
 'Sep 1, 2008',
 'Jan 31, 2018',
 'Jul 19, 2017',
 'Aug 6, 2015',
 'Aug 1, 2012',
 'Sep 25, 2020',
 'Aug 31, 2012',
 'Jul 27, 2016',
 'Aug 10, 2008',
 'Jul 5, 2013',
 'Jul 18, 2012',
 'Aug 9, 2016',
 'May 1, 2012',
 'Jul 1, 2008',
 'Aug 17, 2020',
 'Sep 2, 2014',
 'Jun 9, 2011',
 'Jul 4, 2019',
 'Jan 20, 2017',
 'Sep 4, 2020',
 'Jul 18, 2019',
 'Jul 7, 2017',
 'Jul 15, 2020',
 'Jul 1, 2020',
 'Jul 12, 2018',
 'Jul 19, 2013',
 'Jun 9, 2018',
 'Aug 12, 2020',
 'Jun 8, 2020',
 'Jul 8, 2015',
 'Aug 28, 2020',
 'Jan 1, 2011',
 'Aug 8, 2019',
 'Aug 21, 2015',
 'Sep 18, 2020',
 'Jul 14, 2017',
 'Jan 28, 2020',
 'Aug 2, 2018',
 'Jul 1, 2013',
 'Aug 31, 2016',
 'Sep 24, 2020',
 'Jul 22, 2016',
 'Aug 24, 2020',
 'Jan 5, 2017',
 'Jan 14, 2015',
 'Jul 5, 2018',
 'Jan 1, 2020',
 'Oct 5, 2020',
 'Jan 4, 2016',
 'Sep 1, 2020',
 'Sep 1, 2015',
 'Aug 14, 2019',
 'Jan 5, 2018',
 'Aug 1, 2018',
 'Jul 5, 2017',
 'Jul 30, 2013',
 'Jul 3, 2013',
 'Feb 10, 2010',
 'Jul 30, 2019',
 'Aug 31, 2015',
 'Jul 18, 2017',
 'Aug 24, 2012',
 'Jun 27, 2017',
 'Jun 1, 2011',
 'Aug 17, 2018',
 'Jun 18, 2018',
 'Jul 28, 2017',
 'Sep 9, 2020',
 'Aug 28, 2017',
 'Jan 1, 2019',
 'Jun 29, 2019',
 'Jul 23, 2019',
 'Sep 14, 2020',
 'Jan 29, 2020',
 'Jun 20, 2015',
 'Apr 29, 2015',
 'Sep 2, 2020',
 'Jul 10, 2019',
 'Jul 2, 2018',
 'Aug 3, 2016',
 'Aug 9, 2012',
 'May 17, 2019',
 'Sep 13, 2012',
 'Feb 2, 2015',
 'Aug 7, 2019',
 'Aug 11, 2015',
 'Aug 31, 2018',
 'Aug 16, 2011',
 'Jul 12, 2016',
 'Jul 16, 2018',
 'Jul 7, 2019',
 'Jan 17, 2020',
 'Sep 23, 2020',
 'Jul 3, 2018',
 'Aug 13, 2020',
 'Jul 17, 2019',
 'Aug 13, 2015',
 'Jul 23, 2018',
 'Jul 2, 2019',
 'Aug 1, 2009',
 'Jan 6, 2018',
 'Jan 1, 2017',
 'Jan 21, 2015',
 'Jul 11, 2018',
 'Jan 15, 2019',
 'Sep 5, 2020',
 'Sep 22, 2020',
 'Jan 1, 2007',
 'Sep 1, 2013',
 'Aug 22, 2020',
 'Aug 14, 2020',
 'Jul 11, 2017',
 'Jan 2, 2020',
 'Jul 24, 2018',
 'Jan 8, 2016',
 'Jul 24, 2017',
 'Jul 27, 2020',
 'Aug 1, 2019',
 'Jul 8, 2017',
 'Sep 8, 2020',
 'Sep 19, 2020',
 'Jan 16, 2015',
 'Aug 18, 2015',
 'Jul 3, 2019',
 'Aug 8, 2018',
 'Feb 18, 2020',
 'Jul 4, 2017',
 'Aug 7, 2015',
 'Dec 13, 2014',
 'Jul 4, 2018',
 'Aug 5, 2019',
 'Jul 17, 2018',
 'Jul 20, 2016',
 'Aug 29, 2020',
 'Jul 9, 2019',
 'Aug 2, 2019',
 'Sep 7, 2020',
 'Jul 2, 2015',
 'Aug 18, 2017',
 'Jun 30, 2014',
 'Aug 18, 2009',
 'Sep 2, 2013',
 'Jan 30, 2017',
 'Jul 8, 2019',
 'Aug 11, 2011',
 'Jul 14, 2011',
 'Jun 30, 2020',
 'Sep 29, 2020',
 'Aug 4, 2020',
 'Oct 6, 2020',
 'Mar 22, 2017',
 'Aug 26, 2020',
 'Jan 2, 2019',
 'Jun 27, 2014',
 'Jun 20, 2018',
 'Aug 26, 2017',
 'Jan 31, 2019',
 'Jan 12, 2016',
 'Jun 21, 2018',
 'Aug 29, 2018',
 'Aug 11, 2017',
 'Jul 17, 2017',
 'Jul 13, 2018',
 'Jan 31, 2017',
 'Jul 12, 2014',
 'Jul 9, 2017',
 'Aug 2, 2016',
 'Jun 15, 2017',
 'Jul 20, 2015',
 'Sep 20, 2020',
 'Jul 31, 2018',
 'Jul 21, 2020',
 'Jul 15, 2018',
 'Aug 30, 2020',
 'Jul 31, 2017',
 'Feb 14, 2013',
 'Feb 19, 2018',
 'Jul 13, 2017',
 'Jul 4, 2014',
 'Aug 6, 2020',
 'Aug 29, 2012',
 'Jan 11, 2013',
 'Jul 11, 2019',
 'Feb 14, 2019',
 'Jul 11, 2011',
 'Sep 1, 2014',
 'Aug 21, 2019',
 'Jan 8, 2019',
 'Aug 6, 2018',
 'Jun 18, 2015',
 'Aug 10, 2018',
 'Jul 14, 2019',
 'Jan 1, 2015',
 'Jul 23, 2014',
 'Feb 1, 2017',
 'Aug 25, 2015',
 'Jan 10, 2016',
 'Jul 5, 2019',
 'Jul 22, 2019',
 'Jul 4, 2016',
 'Jan 1, 2010',
 'Sep 3, 2019',
 'Aug 22, 2014',
 'Aug 23, 2019',
 'Aug 2, 2017',
 'Aug 11, 2020',
 'Mar 1, 2012',
 'Jul 12, 2017',
 'Jan 12, 2018',
 'Feb 4, 2015',
 'Aug 28, 2016',
 'Jun 26, 2019',
 'Jul 5, 2016',
 'Jan 3, 2017',
 'Aug 15, 2016',
 'Aug 1, 2010',
 'Jul 15, 2019',
 'Jun 11, 2018',
 'Feb 1, 2016',
 'Jan 17, 2018',
 'Aug 26, 2015',
 'Jan 13, 2015',
 'Aug 31, 2020',
 'Jul 3, 2015',
 'Jul 31, 2016',
 'Jul 26, 2019',
 'Aug 31, 2019',
 'Aug 21, 2020',
 'Sep 15, 2020',
 'Jan 13, 2020',
 'Jul 27, 2015',
 'Sep 10, 2020',
 'Aug 7, 2020',
 'Jan 31, 2014',
 'Aug 23, 2018',
 'Aug 30, 2013',
 'Jan 17, 2019',
 'Jun 8, 2018',
 'Aug 25, 2020',
 'Jan 1, 2002',
 'Feb 19, 2019',
 'Jan 17, 2017',
 'Jul 20, 2019',
 'Jan 25, 2020',
 'Jun 21, 2019',
 'Aug 4, 2019',
 'Sep 16, 2020',
 'Jun 25, 2016',
 'Jun 29, 2016',
 'Jul 16, 2019',
 'Jan 13, 2017',
 'Aug 29, 2019',
 'Jan 25, 2016',
 'Jul 27, 2018',
 'Jul 20, 2018',
 'Jul 14, 2014',
 'Jul 15, 2017',
 'Jan 11, 2019',
 'Aug 21, 2018',
 'Sep 12, 2020',
 'Sep 17, 2020',
 'Sep 9, 2015',
 'Feb 5, 2019',
 'Jan 22, 2016',
 'Apr 10, 2013',
 'Jul 16, 2015',
 'May 21, 2019',
 'Jun 25, 2019',
 'Jun 26, 2020',
 'Aug 20, 2018',
 'Mar 18, 2019',
 'Feb 28, 2020',
 'Sep 30, 2020',
 'Jan 27, 2017',
 'Aug 5, 2020',
 'Jan 7, 2020',
 'Jan 7, 2015',
 'Jul 3, 2017',
 'Jan 29, 2019',
 'Oct 10, 2011',
 'Jun 12, 2017',
 'Aug 27, 2018',
 'Jan 10, 2019',
 'Jul 26, 2018',
 'Jun 12, 2019',
 'Jan 17, 2012',
 'Jan 7, 2019',
 'Jul 13, 2019',
 'Feb 5, 2016',
 'Oct 3, 2020',
 'Aug 14, 2017',
 'Aug 16, 2017',
 'Jul 25, 2018',
 'Aug 16, 2020',
 'Jun 27, 2012',
 'Feb 4, 2009',
 'Jul 1, 2007',
 'Jul 6, 2017',
 'Jan 25, 2014',
 'Aug 13, 2018',
 'Jan 10, 2013',
 'Aug 6, 2019',
 'Jul 7, 2018',
 'Jun 19, 2017',
 'Aug 23, 2020',
 'Oct 2, 2020',
 'Jan 31, 2020',
 'Jan 22, 2018',
 'Apr 10, 2018',
 'Jan 29, 2015',
 'Aug 13, 2017',
 'Aug 26, 2016',
 'Oct 1, 2014',
 'Oct 14, 2015',
 'Jan 26, 2016',
 'Jun 16, 2017',
 'Sep 24, 2013',
 'Jan 28, 2019',
 'Aug 5, 2017',
 'Jan 15, 2020',
 'Jan 18, 2019',
 'Jun 14, 2017',
 'Jun 3, 2013',
 'Jul 8, 2016',
 'Aug 1, 2017',
 'Aug 2, 2015',
 'Jan 10, 2018',
 'Jul 28, 2019',
 'Jan 9, 2020',
 'Jan 15, 2018',
 'Jan 16, 2020',
 'Feb 27, 2018',
 'Aug 1, 2020',
 'Aug 30, 2016',
 'Feb 28, 2019',
 'Jul 4, 2013',
 'Jul 20, 2017',
 'Aug 18, 2020',
 'Jul 24, 2019',
 'Jul 3, 2016',
 'Jul 9, 2016',
 'Aug 2, 2014',
 'Sep 11, 2020',
 'Jan 20, 2016',
 'Jan 11, 2020',
 'Jan 3, 2018',
 'Jul 1, 2009',
 'May 31, 2019',
 'Aug 20, 2020',
 'Aug 26, 2019',
 'Aug 22, 2007',
 'Aug 25, 2018',
 'Jan 1, 2008',
 'Feb 10, 2020',
 'Jun 12, 2015',
 'Jul 11, 2014',
 'Jul 6, 2019',
 'Aug 19, 2020',
 'Aug 21, 2017',
 'Aug 2, 2020',
 'Jun 9, 2016',
 'Sep 28, 2020',
 'Jul 13, 2013',
 'Jan 27, 2019',
 'Aug 25, 2017',
 'May 17, 2016',
 'Feb 7, 2020',
 'Aug 4, 2017',
 'Sep 3, 2020',
 'Aug 27, 2015',
 'Jul 11, 2016',
 'Jul 5, 2014',
 'Jan 30, 2014',
 'Aug 8, 2017',
 'Aug 8, 2016',
 'Jan 31, 2016',
 'Jul 12, 2015',
 'Jul 19, 2019',
 'Jan 10, 2020',
 'Dec 27, 2017',
 'Jan 6, 2017',
 'Jul 25, 2019',
 'Aug 12, 2019',
 'Feb 27, 2019',
 'Aug 29, 2017',
 'Jul 10, 2015',
 'Jul 18, 2015',
 'Sep 21, 2020',
 'Jul 9, 2018',
 'Jan 10, 2014',
 'Jul 27, 2019',
 'Jul 29, 2014',
 'Aug 28, 2018',
 'Nov 1, 2016',
 'Aug 17, 2016',
 'Aug 16, 2016',
 'Jul 29, 2019',
 'Aug 23, 2017',
 'Jan 25, 2017',
 'Oct 2, 2018',
 'Aug 1, 2016',
 'Jul 29, 2020',
 'Feb 2, 2017',
 'Oct 7, 2018',
 'Aug 3, 2018',
 'Feb 15, 2018',
 'Jul 10, 2017',
 'Jan 14, 2020',
 'Jan 1, 2016',
 'Feb 3, 2016',
 'Aug 1, 2011',
 'Jul 21, 2014',
 'Mar 28, 2018',
 'Jul 21, 2018',
 'Jul 3, 2014',
 'Jan 21, 2020',
 'Aug 16, 2018',
 'Jan 1, 2014',
 'Jun 22, 2017',
 'Jul 30, 2018',
 'Jun 24, 2020',
 'Oct 4, 2020',
 'Aug 7, 2018',
 'Aug 4, 2014',
 'Aug 15, 2017',
 'Dec 1, 2011',
 'Jan 4, 2017',
 'Aug 9, 2019',
 'Jan 20, 2020',
 'Jan 25, 2019',
 'Aug 26, 2014',
 'Mar 3, 2017',
 'Aug 4, 2018',
 'Feb 25, 2012',
 'Feb 17, 2020',
 'Jul 6, 2018',
 'Jul 2, 2014',
 'Aug 10, 2020',
 'Jun 29, 2018',
 'Jun 22, 2012',
 'Feb 20, 2019',
 'Jul 18, 2014',
 'Feb 12, 2020',
 'May 28, 2012',
 'Jun 23, 2019',
 'Aug 2, 2013',
 'Jul 16, 2020',
 'Feb 20, 2020',
 'Mar 6, 2020',
 'Sep 13, 2020',
 'Jan 18, 2016',
 'Jan 2, 2013',
 'Aug 22, 2015',
 'Jul 31, 2013',
 'Sep 6, 2020',
 'Jan 19, 2018',
 'Aug 7, 2017',
 'Nov 29, 2014',
 'Jun 10, 2015',
 'Sep 12, 2019',
 'Jan 23, 2020',
 'Mar 10, 2019',
 'Aug 6, 2010',
 'Aug 13, 2019',
 'Jul 31, 2015',
 'Jun 26, 2015',
 'Jun 18, 2020',
 'Sep 15, 2016',
 'Jan 27, 2020',
 'Aug 23, 2016',
 'Aug 15, 2019',
 'Jan 1, 2012',
 'Jul 7, 2009',
 'Oct 1, 2020',
 'Feb 13, 2019',
 'Jul 6, 2020',
 'Feb 28, 2018',
 'Dec 4, 2014',
 'Aug 9, 2014',
 'Aug 10, 2017',
 'Jan 20, 2019',
 'Jun 24, 2017',
 'Sep 8, 2014',
 'Jul 25, 2017',
 'Aug 24, 2015',
 'Dec 6, 2016',
 'Aug 12, 2018',
 'Aug 30, 2019',
 'Jun 26, 2018',
 'Jan 1, 2009',
 'Oct 7, 2020',
 'Oct 24, 2014',
 'Jan 21, 2019',
 'Nov 1, 2012',
 'Jan 14, 2016',
 'Jul 19, 2012',
 'Jan 9, 2016',
 'Aug 12, 2017',
 'Aug 30, 2017',
 'Apr 6, 2020',
 'Jan 1, 2013',
 'Jun 28, 2019',
 'Aug 20, 2014',
 'Jun 23, 2020',
 'Dec 7, 2011',
 'Jan 19, 2017',
 'Feb 22, 2019',
 'Jun 8, 2012',
 'Oct 13, 2016',
 'Jan 7, 2013',
 'Jul 28, 2020',
 'Apr 17, 2013',
 'Jan 5, 2014',
 'Jan 1, 2005',
 'Aug 11, 2016',
 'Mar 20, 2017',
 'Jun 22, 2018',
 'Jul 6, 2016',
 'Nov 5, 2018',
 'Aug 24, 2019',
 'Jan 14, 2019',
 'Dec 27, 2018',
 'Aug 22, 2017',
 'Apr 1, 2011',
 'Jan 26, 2017',
 'Jul 7, 2020',
 'Aug 28, 2019',
 'Jun 6, 2014',
 'Jul 7, 2016',
 'Aug 22, 2019',
 'Jun 11, 2019',
 'Jan 5, 2020',
 'Dec 9, 2019',
 'Jul 23, 2016',
 'Aug 14, 2018',
 'Feb 15, 2017',
 'Nov 13, 2019',
 'Mar 1, 2014',
 'May 23, 2019',
 'Jun 22, 2015',
 'Jan 30, 2019',
 'Jun 8, 2016',
 'Aug 3, 2019',
 'Sep 30, 2015',
 'Apr 27, 2013',
 'Jan 16, 2014',
 'Dec 10, 2013',
 'Jul 18, 2016',
 'Nov 22, 2019',
 'Jan 28, 2009',
 'Jul 25, 2016',
 'Jan 24, 2020',
 'Jun 25, 2020',
 'Jan 18, 2018',
 'Jul 12, 2013',
 'Jan 3, 2020',
 'Feb 20, 2015',
 'Aug 13, 2013',
 'Jun 29, 2017',
 'Aug 25, 2014',
 'Dec 14, 2018',
 'Jul 14, 2018',
 'Jan 3, 2012',
 'May 29, 2007',
 'Aug 12, 2015',
 'Sep 14, 2018',
 'Jan 23, 2006',
 'Jun 26, 2017',
 'Jun 30, 2017',
 'Dec 17, 2016',
 'Mar 11, 2020',
 'Aug 24, 2016',
 'Feb 6, 2020',
 'Jan 6, 2016',
 'Jan 27, 2016',
 'Jun 20, 2017',
 'Feb 22, 2017',
 'Jul 30, 2020',
 'Jul 24, 2020',
 'Aug 27, 2020',
 'May 30, 2017',
 'Aug 8, 2020',
 'Jan 28, 2014',
 'Jul 28, 2016',
 'Feb 15, 2016',
 'Jul 28, 2014',
 'Jan 11, 2016',
 'Jul 29, 2012',
 'Jan 23, 2019',
 'Feb 25, 2020',
 'Jan 9, 2018',
 'Feb 18, 2017',
 'Jan 14, 2017',
 'Jul 4, 2015',
 'Jul 17, 2020',
 'Mar 15, 2019',
 'Dec 2, 2015',
 'Apr 5, 2011',
 'Jul 21, 2016',
 'Jan 3, 2019',
 'Feb 27, 2017',
 'Jun 21, 2017',
 'Aug 1, 2004',
 'Feb 1, 2019',
 'Jun 11, 2014',
 'Aug 16, 2015',
 'Apr 30, 2018',
 'Aug 20, 2019',
 'May 17, 2017',
 'Jun 1, 2009',
 'Jan 9, 2017',
 'Dec 14, 2017',
 'Jan 21, 2016',
 'Jan 16, 2018',
 'Aug 14, 2014',
 'Jun 4, 2020',
 'Jun 19, 2016',
 'Dec 20, 2017',
 'Jan 15, 2015',
 'Feb 8, 2018',
 'Jul 8, 2014',
 'Sep 6, 2018',
 'May 8, 2018',
 'Feb 14, 2020',
 'Feb 7, 2019',
 'Jul 15, 2016',
 'Aug 18, 2018',
 'Feb 4, 2017',
 'Oct 16, 2019',
 'Jul 9, 2020',
 'Mar 1, 2018',
 'Jul 22, 2020',
 'Jul 3, 2020',
 'Jun 1, 2019',
 'Apr 13, 2017',
 'Aug 16, 2019',
 'Aug 9, 2017',
 'Feb 26, 2019',
 'Feb 16, 2018',
 'Jul 10, 2009',
 'Jan 20, 2018',
 'Dec 11, 2019',
 'Sep 1, 2011',
 'Jan 25, 2018',
 'Jan 16, 2019',
 'Feb 8, 2019',
 'Jun 25, 2018',
 'Jul 19, 2016',
 'Jul 17, 2013',
 'Jun 14, 2016',
 'Jul 31, 2019',
 'Jun 1, 2010',
 'Mar 31, 2015',
 'Feb 7, 2018',
 'Aug 3, 2020',
 'Jul 29, 2016',
 'Sep 26, 2020',
 'Jan 23, 2015',
 'Mar 30, 2018',
 'Jan 26, 2018',
 'Sep 1, 2019',
 'Feb 7, 2013',
 'Jan 2, 2018',
 'Sep 1, 2017',
 'Jan 2, 2015',
 'Jan 23, 2017',
 'Jul 29, 2018',
 'Jul 21, 2019',
 'Jan 4, 2019',
 'Aug 30, 2018',
 'Apr 5, 2016',
 'Jan 26, 2019',
 'Jan 5, 2019',
 'Jun 19, 2018',
 'Jun 23, 2017',
 'Feb 1, 2018',
 'Jan 30, 2012',
 'Jul 14, 2016',
 'Mar 3, 2016',
 'Jan 5, 2016',
 'Jul 8, 2020',
 'Jan 22, 2020',
 'Jul 31, 2014',
 'Aug 11, 2019',
 'Jan 13, 2016',
 'Jan 6, 2019',
 'Jun 24, 2014',
 'Mar 10, 2017',
 'Feb 3, 2020',
 'Mar 21, 2014',
 'Dec 6, 2018',
 'Jun 26, 2014',
 'Jul 14, 2020',
 'Jun 15, 2016',
 'Jul 19, 2015',
 'Feb 5, 2020',
 'Jan 15, 2017',
 'Dec 23, 2014',
 'Feb 29, 2020',
 'Aug 19, 2019',
 'Aug 13, 2014',
 'Jun 9, 2017',
 'Jan 31, 2013',
 'Jan 6, 2020',
 'Jan 4, 2018',
 'Jun 30, 2016',
 'Jan 9, 2013',
 'Feb 11, 2020',
 'Feb 2, 2019',
 'Dec 13, 2017',
 'Aug 14, 2015',
 'Jul 8, 2011',
 'Mar 8, 2013',
 'Sep 27, 2020',
 'Jul 15, 2015',
 'Apr 25, 2013',
 'Feb 27, 2020',
 'Jun 30, 2015',
 'Jun 18, 2014',
 'Jan 12, 2020',
 'Jan 24, 2017',
 'Sep 5, 2016',
 'Jan 8, 2020',
 'Apr 10, 2019',
 'Aug 10, 2015',
 'Oct 8, 2019',
 'Nov 6, 2019',
 'Feb 8, 2020',
 'Dec 7, 2015',
 'Feb 21, 2019',
 'Aug 25, 2016',
 'Jul 18, 2018',
 'Aug 15, 2014',
 'Aug 17, 2017',
 'Dec 21, 2018',
 'Jun 1, 2020',
 'Jun 10, 2017',
 'Aug 15, 2018',
 'Jun 23, 2015',
 'Jan 15, 2014',
 'Jan 30, 2015',
 'Dec 18, 2014',
 'Aug 27, 2016',
 'Jan 14, 2013',
 'Oct 24, 2013',
 'Jun 17, 2016',
 'Mar 25, 2015',
 'Nov 30, 2018',
 'Aug 5, 2018',
 'Mar 4, 2020',
 'Jan 19, 2020',
 'Aug 7, 2014',
 'Aug 4, 2015',
 'Jan 22, 2019',
 'Dec 21, 2016',
 'Feb 2, 2020',
 'Jul 2, 2017',
 'Jul 25, 2015',
 'Jan 11, 2014',
 'Jan 9, 2019',
 'Jul 29, 2013',
 'Feb 4, 2019',
 'Feb 19, 2017',
 'Mar 2, 2020',
 'Mar 5, 2014',
 'May 27, 2018',
 'Sep 3, 2018',
 'Aug 25, 2019',
 'Jun 10, 2019',
 'Feb 1, 2020',
 'Dec 23, 2016',
 'Dec 2, 2019',
 'Oct 10, 2016',
 'Jul 7, 2015',
 'May 29, 2017',
 'Jun 1, 2014',
 'Sep 4, 2019',
 'Jun 1, 2012',
 'Jul 13, 2020',
 'Dec 12, 2016',
 'Jul 9, 2015',
 'Jun 1, 2017',
 'May 18, 2018',
 'Aug 4, 2016',
 'Feb 9, 2018',
 'Aug 27, 2017',
 'Jul 30, 2015',
 'Jul 26, 2016',
 'May 24, 2016',
 'Sep 11, 2018',
 'Jan 19, 2016',
 'Feb 6, 2019',
 'Dec 12, 2019',
 'Jul 17, 2015',
 'Jan 18, 2020',
 'Jul 12, 2012',
 'Jun 26, 2016',
 'Sep 1, 2010',
 'Jan 24, 2018',
 'Feb 2, 2018',
 'Aug 24, 2017',
 'Jan 29, 2017',
 'Apr 15, 2014',
 'Jul 1, 2006',
 'Jan 18, 2017',
 'Jan 4, 2020',
 'Jun 28, 2018',
 'Feb 4, 2014',
 'Oct 11, 2016',
 'Aug 17, 2019',
 'Jul 26, 2017',
 'Jun 5, 2018',
 'Jun 19, 2020',
 'May 7, 2019',
 'Jun 13, 2018',
 'Jul 7, 2014',
 'Jul 23, 2020',
 'Oct 1, 2011',
 'Mar 20, 2014',
 'Jan 24, 2019',
 'Feb 4, 2020',
 'Jun 29, 2020',
 'Aug 23, 2014',
 'Jun 17, 2019',
 'Sep 13, 2015',
 'Feb 15, 2019',
 'Aug 20, 2016',
 'Mar 25, 2014',
 'Jan 8, 2015',
 'Dec 18, 2017',
 'Jul 30, 2016',
 'Oct 1, 2019',
 'Aug 10, 2019',
 'Jul 10, 2020',
 'Sep 19, 2019',
 'Feb 1, 2011',
 'Nov 22, 2016',
 'Jul 31, 2020',
 'Sep 6, 2017',
 'Jan 11, 2017',
 'Jan 16, 2016',
 'Jul 28, 2018',
 'Feb 1, 2013',
 'Jan 30, 2016',
 'Jul 2, 2020',
 'Jul 20, 2020',
 'Mar 21, 2019',
 'Aug 27, 2019',
 'May 13, 2015',
 'Feb 2, 2016',
 'Nov 16, 2017',
 'Jul 2, 2012',
 'Jan 10, 2015',
 'Sep 9, 2019',
 'Feb 3, 2017',
 'Jan 28, 2015',
 'Jul 23, 2017',
 'Jul 25, 2012',
 'Feb 26, 2020',
 'Jul 19, 2020',
 'Apr 1, 2016',
 'Nov 4, 2018',
 'Jun 28, 2020',
 'Jul 1, 2003',
 'Dec 10, 2018',
 'Jul 5, 2015',
 'Jul 10, 2016',
 'Aug 9, 2013',
 'Jul 22, 2014',
 'Nov 19, 2019',
 'Jan 6, 2014',
 'Jul 28, 2015',
 'Jun 8, 2017',
 'Dec 21, 2019',
 'Jan 25, 2010',
 'Oct 16, 2016',
 'Jun 16, 2015',
 'Dec 7, 2018',
 'Aug 23, 2013',
 'Sep 6, 2016',
 'Jan 28, 2016',
 'Jul 11, 2015',
 'Sep 11, 2019',
 'Jun 28, 2017',
 'Apr 1, 2020',
 'Jun 27, 2019',
 'Apr 25, 2017',
 'Jul 18, 2020',
 'May 30, 2018',
 'Dec 5, 2019',
 'Jul 27, 2017',
 'Jul 9, 2013',
 'Dec 27, 2016',
 'Nov 20, 2019',
 'Dec 25, 2013',
 'Sep 4, 2017',
 'Dec 28, 2015',
 'Jan 7, 2016',
 'Jan 23, 2018',
 'Aug 6, 2017',
 'Jan 7, 2017',
 'Jan 11, 2018',
 'Nov 12, 2019',
 'Oct 28, 2017',
 'Nov 22, 2010',
 'Jan 20, 2012',
 'Jun 12, 2020',
 'Jan 29, 2018',
 'Aug 6, 2014',
 'Jan 8, 2018',
 'Jul 12, 2020',
 'Jun 18, 2019',
 'Jan 2, 2014',
 'Jan 22, 2015',
 'May 2, 2016',
 'Sep 1, 2009',
 'May 15, 2018',
 'Sep 22, 2019',
 'Aug 22, 2018',
 'Dec 1, 2015',
 'Dec 23, 2013',
 'Aug 25, 2012',
 'Sep 18, 2019',
 'May 5, 2015',
 'Jul 2, 2016',
 'Mar 2, 2018',
 'Jul 22, 2018',
 'Jan 12, 2019',
 'Jun 1, 2018',
 'Feb 11, 2016',
 'Aug 15, 2020',
 'Jun 17, 2017',
 'Jun 12, 2018',
 'Feb 17, 2017',
 'May 29, 2019',
 'Feb 27, 2014',
 'Jul 6, 2013',
 'Jul 29, 2017',
 'Jul 28, 2013',
 'Mar 1, 2019',
 'Sep 4, 2012',
 'May 1, 2017',
 'Nov 22, 2017',
 'Jan 6, 2015',
 'Jan 15, 2009',
 'Jan 4, 2013',
 'Jun 10, 2020',
 'Jun 11, 2020',
 'Oct 13, 2014',
 'Dec 9, 2013',
 'Oct 14, 2019',
 'Sep 30, 2016',
 'Feb 5, 2018',
 'May 3, 2019',
 'Jun 10, 2016',
 'Sep 21, 2018',
 'Oct 8, 2016',
 'Feb 13, 2018',
 'Mar 6, 2019',
 'Dec 12, 2017',
 'May 1, 2015',
 'Nov 28, 2014',
 'Dec 1, 2017',
 'Dec 17, 2013',
 'Aug 19, 2016',
 'Aug 20, 2015',
 ...]

In [45]:
df['Loan Date End'].unique().tolist()

[nan,
 'Jun 30, 2021',
 'Dec 31, 2020',
 'Jan 30, 2021',
 'Jun 30, 2022',
 'May 31, 2021',
 'Jul 5, 2021',
 'Dec 31, 2021',
 'Jul 1, 2021',
 'Jan 1, 2021',
 'Aug 31, 2021',
 'Jan 31, 2021',
 'Dec 30, 2021',
 'Jun 23, 2021',
 'Jan 3, 2021',
 'Nov 27, 2021',
 'Jan 17, 2021',
 'Jun 30, 2023',
 'Jul 31, 2021',
 'Nov 22, 2020',
 'May 31, 2022',
 'Dec 30, 2020',
 'Jan 4, 2021',
 'Nov 30, 2020',
 'Aug 1, 2021']

In [51]:
df['Value'].unique().tolist()

['€103.5M',
 '€63M',
 '€120M',
 '€129M',
 '€132M',
 '€111M',
 '€120.5M',
 '€102M',
 '€185.5M',
 '€110M',
 '€113M',
 '€90.5M',
 '€82M',
 '€17.5M',
 '€83.5M',
 '€33.5M',
 '€114.5M',
 '€78M',
 '€103M',
 '€109M',
 '€92M',
 '€10M',
 '€76.5M',
 '€89.5M',
 '€87.5M',
 '€79.5M',
 '€124M',
 '€114M',
 '€95M',
 '€92.5M',
 '€105.5M',
 '€88.5M',
 '€85M',
 '€81.5M',
 '€26M',
 '€21M',
 '€56M',
 '€67.5M',
 '€53M',
 '€36.5M',
 '€51M',
 '€65.5M',
 '€46.5M',
 '€61.5M',
 '€72.5M',
 '€77.5M',
 '€43.5M',
 '€32.5M',
 '€36M',
 '€32M',
 '€54M',
 '€49.5M',
 '€57M',
 '€66.5M',
 '€74.5M',
 '€71.5M',
 '€121M',
 '€99M',
 '€67M',
 '€86.5M',
 '€93.5M',
 '€70M',
 '€62M',
 '€66M',
 '€58M',
 '€44M',
 '€81M',
 '€37M',
 '€14.5M',
 '€46M',
 '€47.5M',
 '€52.5M',
 '€54.5M',
 '€34.5M',
 '€57.5M',
 '€51.5M',
 '€44.5M',
 '€55M',
 '€48M',
 '€60.5M',
 '€63.5M',
 '€61M',
 '€29M',
 '€58.5M',
 '€55.5M',
 '€42M',
 '€40.5M',
 '€43M',
 '€45.5M',
 '€34M',
 '€26.5M',
 '€42.5M',
 '€35.5M',
 '€45M',
 '€41.5M',
 '€40M',
 '€11M',
 '€13.5M',
 '€29.5M',
 '€27M',
 '€15.5M',
 '€38.5M',
 '€52M',
 '€33M',
 '€19M',
 '€73.5M',
 '€38M',
 '€35M',
 '€47M',
 '€24M',
 '€30.5M',
 '€18M',
 '€28M',
 '€25.5M',
 '€25M',
 '€31M',
 '€23.5M',
 '€30M',
 '€31.5M',
 '€22.5M',
 '€28.5M',
 '€4M',
 '€12.5M',
 '€37.5M',
 '€27.5M',
 '€16M',
 '€15M',
 '€20.5M',
 '€22M',
 '€3.4M',
 '€5M',
 '€56.5M',
 '€62.5M',
 '€0',
 '€39M',
 '€24.5M',
 '€21.5M',
 '€13M',
 '€8M',
 '€20M',
 '€8.5M',
 '€2.9M',
 '€9M',
 '€4.6M',
 '€50M',
 '€23M',
 '€18.5M',
 '€7M',
 '€19.5M',
 '€5.5M',
 '€7.5M',
 '€3.8M',
 '€14M',
 '€10.5M',
 '€16.5M',
 '€3.6M',
 '€9.5M',
 '€39.5M',
 '€17M',
 '€12M',
 '€11.5M',
 '€4.9M',
 '€3M',
 '€1.9M',
 '€6.5M',
 '€1.7M',
 '€2.4M',
 '€3.1M',
 '€6M',
 '€3.7M',
 '€4.7M',
 '€4.3M',
 '€2.1M',
 '€1.2M',
 '€1.8M',
 '€4.8M',
 '€3.2M',
 '€1.3M',
 '€825K',
 '€2.3M',
 '€1.5M',
 '€3.9M',
 '€2.6M',
 '€3.5M',
 '€2.8M',
 '€2.7M',
 '€4.4M',
 '€4.1M',
 '€950K',
 '€1.6M',
 '€625K',
 '€1.1M',
 '€4.5M',
 '€4.2M',
 '€2.2M',
 '€3.3M',
 '€1.4M',
 '€2M',
 '€475K',
 '€925K',
 '€750K',
 '€725K',
 '€2.5M',
 '€1M',
 '€350K',
 '€525K',
 '€600K',
 '€850K',
 '€800K',
 '€550K',
 '€250K',
 '€400K',
 '€425K',
 '€575K',
 '€210K',
 '€325K',
 '€900K',
 '€875K',
 '€650K',
 '€700K',
 '€500K',
 '€975K',
 '€375K',
 '€775K',
 '€275K',
 '€180K',
 '€450K',
 '€675K',
 '€150K',
 '€240K',
 '€300K',
 '€130K',
 '€220K',
 '€200K',
 '€110K',
 '€170K',
 '€230K',
 '€90K',
 '€120K',
 '€80K',
 '€190K',
 '€140K',
 '€160K',
 '€100K',
 '€60K',
 '€50K',
 '€70K',
 '€45K',
 '€35K',
 '€40K',
 '€25K',
 '€20K',
 '€15K',
 '€30K',
 '€9K']